package com.example.birdgame3;

import com.example.birdgame3.BirdGame3.BirdType;
import com.example.birdgame3.BirdGame3.MapVariant;
import com.example.birdgame3.BirdGame3.MapType;
import com.example.birdgame3.BirdGame3.StageRandomPool;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class LanProtocolTest {
    @Test
    void startMessageCarriesNegotiatedInternetInputDelay() throws IOException {
        final int[] receivedDelay = {-1};
        final MapVariant[] receivedVariant = {MapVariant.STANDARD};
        BirdGame3 game = new BirdGame3() {
            @Override
            void onLanStartMatch(MapType map, MapVariant variant, long seed, int inputDelayTicks, NetworkSimulationConfig simulationConfig,
                                 boolean[] connected, BirdType[] birds, String[] skinKeys) {
                receivedDelay[0] = inputDelayTicks;
                receivedVariant[0] = variant;
            }
        };
        byte[] payload = LanProtocol.buildMessage(LanProtocol.MSG_START, out -> {
            out.writeInt(MapType.CITY.ordinal());
            out.writeInt(MapVariant.PARLIAMENT_ROOFTOPS.ordinal());
            out.writeLong(42L);
            out.writeInt(LockstepSession.INTERNET_INPUT_DELAY_TICKS);
            NetworkSimulationConfig.capture().write(out);
            for (int i = 0; i < 4; i++) {
                out.writeBoolean(i < 2);
                out.writeInt(BirdType.PIGEON.ordinal());
                out.writeUTF("");
            }
        });

        LanPayloadRouter.handleServerPayload(game, payload);

        assertEquals(LockstepSession.INTERNET_INPUT_DELAY_TICKS, receivedDelay[0]);
        assertEquals(MapVariant.PARLIAMENT_ROOFTOPS, receivedVariant[0]);
    }

    @Test
    void mapVoteCarriesVariantAndRandomPool() throws IOException {
        final MapVariant[] receivedVariant = {MapVariant.STANDARD};
        final StageRandomPool[] receivedPool = {StageRandomPool.NONE};
        BirdGame3 game = new BirdGame3() {
            @Override
            void onLanClientMapVote(int slot, MapType map, MapVariant variant, StageRandomPool randomPool) {
                receivedVariant[0] = variant;
                receivedPool[0] = randomPool;
            }
        };
        byte[] payload = LanProtocol.buildMessage(LanProtocol.MSG_MAP_VOTE, out -> {
            out.writeInt(LanProtocol.MAP_RANDOM);
            out.writeInt(MapVariant.STANDARD.ordinal());
            out.writeInt(StageRandomPool.VARIANTS.ordinal());
        });

        LanPayloadRouter.handleClientPayload(game, 2, payload);

        assertEquals(MapVariant.STANDARD, receivedVariant[0]);
        assertEquals(StageRandomPool.VARIANTS, receivedPool[0]);
    }

    @Test
    void framedPayloadRoundTrips() throws IOException {
        byte[] payload = LanProtocol.buildMessage(LanProtocol.MSG_READY, out -> out.writeBoolean(true));

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        LanProtocol.writeFramed(new DataOutputStream(bos), payload);

        byte[] read = LanProtocol.readFramed(new DataInputStream(new ByteArrayInputStream(bos.toByteArray())));
        assertArrayEquals(payload, read);

        DataInputStream in = new DataInputStream(new ByteArrayInputStream(read));
        assertEquals(LanProtocol.MSG_READY, in.readByte());
        assertTrue(in.readBoolean());
    }

    @Test
    void invalidFrameLengthIsRejected() throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        DataOutputStream out = new DataOutputStream(bos);
        out.writeInt(5_000_001);
        out.flush();

        DataInputStream in = new DataInputStream(new ByteArrayInputStream(bos.toByteArray()));
        assertThrows(IOException.class, () -> LanProtocol.readFramed(in));
    }

    @Test
    void lanBirdStateRoundTripsDodgeFields() throws IOException {
        LanBirdState state = new LanBirdState();
        state.attackChargeFrames = 14;
        state.pendingGroundAttackFrames = 5;
        state.pendingGroundAttackVariantOrdinal = 3;
        state.chargingAttackVariantOrdinal = 6;
        state.activeAttackVariantOrdinal = 10;
        state.dodgeTypeOrdinal = 2;
        state.dodgeTimer = 17;
        state.dodgeInvulnerabilityTimer = 9;
        state.dodgeCooldown = 6;
        state.dodgeDirection = -1;
        state.airDodgeAvailable = false;
        state.activeAerialLandingLagFrames = 12;
        state.mockingbirdLoungeReuseTimer = 47;
        state.phoenixLavaReuseTimer = 31;
        state.phoenixFireballFizzleTimer = 13;
        state.phoenixAirSideAimPoseTimer = 17;
        state.phoenixAirSideLandingPrimeTimer = 45;
        state.phoenixAirSideLandingFxTimer = 9;
        state.roadrunnerMomentum = 74.5;
        state.roadrunnerMomentumGraceTimer = 51;
        state.roadrunnerBeepCharging = true;
        state.roadrunnerBeepChargeFrames = 28;
        state.roadrunnerBeepMaxChargeHoldFrames = 6;
        state.roadrunnerRicochetTimer = 9;
        state.roadrunnerRicochetSpeed = 27.5;
        state.roadrunnerDustDevilUsed = true;
        state.roadrunnerRoadBoostTimer = 18;
        state.roadrunnerSlipTimer = 44;
        state.roadrunnerSlipDirection = -1;
        state.roadrunnerRedlineTimer = 73;
        state.roadrunnerRedlineRecoveryTimer = 8;
        state.roadrunnerRedlineCinematic = true;
        state.roadrunnerRedlineDirection = -1;
        state.roadrunnerRedlineStrikeIndex = 4;
        state.roadrunnerRedlineFinalResolved = true;
        state.roadrunnerRedlineStartX = 101.25;
        state.roadrunnerRedlineStartY = 202.5;
        state.roadrunnerRedlineEndX = 303.75;
        state.roadrunnerRedlineEndY = 404.0;
        state.roadrunnerRedlineAnchorX = 505.25;
        state.roadrunnerRedlineAnchorY = 606.5;
        state.roadrunnerRedlineLastStartX = 707.75;
        state.roadrunnerRedlineLastStartY = 808.0;
        state.roadrunnerRedlineLastEndX = 909.25;
        state.roadrunnerRedlineLastEndY = 1001.5;
        state.roadrunnerRedlineCaught[2] = true;
        state.grinchHeartSnatchTimer = 14;
        state.grinchHeartSnatchUltimate = true;
        state.grinchHeartSnatchHit[1] = true;
        state.grinchSleighActive = true;
        state.grinchSleighRiding = true;
        state.grinchSleighTimer = 88;
        state.grinchSleighDirection = -1;
        state.grinchSleighX = 333.25;
        state.grinchSleighY = 444.5;
        state.grinchSleighUltimate = true;
        state.grinchSleighHit[2] = true;
        state.grinchChimneyFlapTimer = 11;
        state.grinchChimneyFlapUltimate = true;
        state.grinchUpSpecialUsed = true;
        state.grinchChimneyFlapHit[3] = true;
        state.grinchPresentActive = true;
        state.grinchPresentX = 555.75;
        state.grinchPresentY = 666.25;
        state.grinchPresentUltimate = true;
        state.grinchPresentAgeFrames = 19;
        state.grinchPresentFuseFrames = 77;
        state.grinchGiftstormTimer = 123;
        state.grinchGiftstormDropIndex = 4;
        state.grinchGiftstormFinalResolved = true;
        state.grinchGiftstormDirection = -1;
        state.grinchGiftstormSleighX = 701.25;
        state.grinchGiftstormSleighY = 202.5;
        state.grinchGiftstormFinalStartX = 111.25;
        state.grinchGiftstormFinalStartY = 222.5;
        state.grinchGiftstormFinalEndX = 333.75;
        state.grinchGiftstormFinalEndY = 444.0;
        state.grinchGiftstormLastDropX = 555.25;
        state.grinchGiftstormLastDropY = 666.5;
        state.grinchGiftstormLastDropKind = 2;
        state.grinchGiftstormDropFxTimer = 18;
        state.grinchGiftstormFinalHit[1] = true;
        state.carrionSwarmTimer = 44;
        state.vultureBlackSkyTimer = 99;
        state.vultureBlackSkySpawnTimer = 7;
        state.vultureBlackSkyCrowsSpawned = 31;
        state.vultureBlackSkyWaveIndex = 5;
        state.vultureBlackSkyFinalHit = true;
        state.vultureBlackSkyHit[3] = true;
        state.isAshenSovereignSkin = true;
        state.penguinBellyCharging = true;
        state.penguinBellyChargeFrames = 41;
        state.penguinBellySlideTimer = 13;
        state.penguinBellyDirection = -1;
        state.penguinRocketTimer = 21;
        state.penguinUpSpecialUsed = true;
        state.penguinSnowFortActive = true;
        state.penguinSnowFortX = 1234.5;
        state.penguinSnowFortY = 2100.25;
        state.penguinSnowFortHealth = 33;
        state.shoebillThrustTimer = 19;
        state.shoebillThrustDirection = -1;
        state.shoebillMarshLiftTimer = 12;
        state.shoebillUpSpecialUsed = true;
        state.shoebillStatueCountered = true;
        state.shoebillCounterBurstTimer = 7;
        state.shoebillFinalStillnessTimer = 88;
        state.shoebillFinalStillnessTargetIndex = 2;
        state.shoebillFinalStillnessStatueX = 600.25;
        state.shoebillFinalStillnessStatueY = 1200.5;
        state.shoebillFinalStillnessBeamStartX = 610.75;
        state.shoebillFinalStillnessBeamStartY = 930.25;
        state.shoebillFinalStillnessBeamTargetX = 720.5;
        state.shoebillFinalStillnessBeamTargetY = 880.75;
        state.shoebillFinalStillnessBeamResolved = true;
        state.turkeyHarvestTribunalTimer = 91;
        state.turkeyHarvestTribunalX = 555.25;
        state.turkeyHarvestTribunalY = 777.5;
        state.turkeyHarvestTribunalFinalResolved = true;
        state.turkeyHarvestTribunalFinalHit[2] = true;
        state.hummingFrenzyTimer = 77;
        state.hummingFrenzyTargetIndex = 1;
        state.hummingFrenzyStrikeIndex = 2;
        state.hummingFrenzyConnectedStrikes = 2;
        state.hummingFrenzyFinalResolved = true;
        state.hummingFrenzyAnchorX = 101.25;
        state.hummingFrenzyAnchorY = 202.5;
        state.hummingFrenzyTargetX = 303.75;
        state.hummingFrenzyTargetY = 404.0;
        state.hummingFrenzyLastStartX = 505.25;
        state.hummingFrenzyLastStartY = 606.5;
        state.hummingFrenzyLastEndX = 707.75;
        state.hummingFrenzyLastEndY = 808.0;
        state.hummingFrenzyHitCooldown[2] = 6;
        state.opiumResourceMeter = 63.5;
        state.opiumNeutralFueled = true;
        state.opiumNeutralReuseTimer = 29;
        state.opiumSideTimer = 11;
        state.opiumSideFueled = true;
        state.opiumSideHit[1] = true;
        state.opiumUpTimer = 8;
        state.opiumUpSpecialUsed = true;
        state.opiumUpFueled = true;
        state.opiumDownReuseTimer = 33;
        state.opiumUltimateTimer = 210;
        state.opiumUltimateCollapsePending = true;
        state.opiumUltimateCloudX = 432.25;
        state.opiumUltimateCloudY = 876.5;
        state.heisenUltimateTimer = 144;
        state.heisenUltimateShatterPending = true;
        state.heisenUltimateVolleyTimer = 25;
        state.heisenUltimateVolleyOriginX = 222.5;
        state.heisenUltimateVolleyOriginY = 333.5;
        state.heisenUltimateVolleyTargetX = 444.5;
        state.heisenUltimateVolleyTargetY = 555.5;
        state.heisenUltimateVolleyHit = true;
        state.opiumDrowsyTimer = 66;
        state.opiumDrowsyOwnerIndex = 2;
        state.opiumDrowsyUltimate = true;
        state.heisenBrittleTimer = 88;
        state.heisenBrittleOwnerIndex = 3;
        state.heisenBrittleUltimate = true;
        state.pigeonCoronationActive = true;
        state.pigeonCoronationTimer = 77;
        state.pigeonCoronationX = 111.25;
        state.pigeonCoronationY = 222.5;
        state.pigeonCoronationFinalResolved = false;
        state.pigeonCoronationStayedInside = true;
        state.pigeonCoronationTickCooldown[3] = 12;
        state.pigeonCoronationFinalHit[0] = true;
        state.pigeonScavengeTimer = 71;
        state.pigeonScavengeHoldFrames = 29;
        state.pigeonScavengeAirborne = true;
        state.pigeonScavengeHitCooldown[2] = 6;
        state.eagleSkySovereignActive = true;
        state.eagleSkySovereignDiving = false;
        state.eagleSkySovereignTimer = 44;
        state.eagleSkySovereignTargetX = 555.25;
        state.eagleSkySovereignTargetY = 666.5;
        state.eagleSkySovereignDiveStartY = 77.75;
        state.eagleSkySovereignHitResolved = true;
        state.eagleSkySovereignHit[2] = true;
        state.falconTerminalVelocityActive = true;
        state.falconTerminalVelocityStriking = true;
        state.falconTerminalVelocityHitAny = false;
        state.falconTerminalVelocityTimer = 5;
        state.falconTerminalVelocityDirection = -1;
        state.falconTerminalVelocityStartX = 910.25;
        state.falconTerminalVelocityStartY = 303.5;
        state.falconTerminalVelocityEndX = 401.75;
        state.falconTerminalVelocityEndY = 700.5;
        state.falconTerminalVelocityHit[1] = true;
        state.razorbillGuillotineTimer = 97;
        state.razorbillGuillotineSlashIndex = 4;
        state.razorbillGuillotineWakeTimer = 66;
        state.razorbillGuillotineFinalResolved = true;
        state.razorbillGuillotineAnchorX = 118.25;
        state.razorbillGuillotineAnchorY = 228.5;
        state.razorbillGuillotineTargetX = 338.75;
        state.razorbillGuillotineTargetY = 448.0;
        state.razorbillGuillotineLastStartX = 558.25;
        state.razorbillGuillotineLastStartY = 668.5;
        state.razorbillGuillotineLastEndX = 778.75;
        state.razorbillGuillotineLastEndY = 888.0;
        state.razorbillGuillotineWakeX1 = 128.5;
        state.razorbillGuillotineWakeX2 = 488.25;
        state.razorbillGuillotineWakeY = 918.75;
        state.razorbillGuillotineHitCooldown[0] = 6;
        state.razorbillGuillotineWakeHitCooldown[2] = 14;
        state.pelicanCargoCount = 2;
        state.pelicanNeutralTimer = 8;
        state.pelicanNeutralReuseTimer = 12;
        state.pelicanNeutralUltimate = true;
        state.pelicanNeutralHit[1] = true;
        state.pelicanSideTimer = 14;
        state.pelicanSideReuseTimer = 21;
        state.pelicanSideDirection = -1;
        state.pelicanSideCargoSpent = 2;
        state.pelicanSideUltimate = true;
        state.pelicanSideHit[2] = true;
        state.pelicanUpTimer = 17;
        state.pelicanUpSpecialUsed = true;
        state.pelicanUpUltimate = true;
        state.pelicanKeelDiveActive = true;
        state.pelicanUpHit[3] = true;
        state.pelicanDownCharging = true;
        state.pelicanDownHoldFrames = 19;
        state.pelicanDownReuseTimer = 25;
        state.pelicanDownUltimate = true;
        state.pelicanBilgeFxTimer = 9;
        state.pelicanBilgeCargoSpent = 2;
        state.pelicanBilgeUltimate = true;
        state.pelicanFullHoldTimer = 144;
        state.pelicanMaelstromTimer = 88;
        state.pelicanMaelstromPulseCooldown = 5;
        state.pelicanMaelstromFinalResolved = true;
        state.pelicanMaelstromCargoSpent = 2;
        state.pelicanMaelstromX = 1234.5;
        state.pelicanMaelstromY = 2222.25;
        state.pelicanMaelstromGeyserFxTimer = 33;
        state.pelicanMaelstromFinalHit[2] = true;
        state.batNeutralReuseTimer = 17;
        state.batWingcutTimer = 9;
        state.batWingcutDirection = -1;
        state.batWingcutFromHang = true;
        state.batWingcutHit[2] = true;
        state.batMoonriseUsed = true;
        state.batSilentDiveTimer = 12;
        state.batSilentFromHang = true;
        state.batSilentHit[1] = true;
        state.batCathedralTimer = 144;
        state.batEchoFxEndX = 777.25;
        state.batEchoFxBounced = true;
        state.ravenQuillCharging = true;
        state.ravenQuillChargeFrames = 18;
        state.ravenNeutralReuseTimer = 22;
        state.ravenSideTimer = 11;
        state.ravenSideDirection = -1;
        state.ravenSideEmpowered = true;
        state.ravenSideStartX = 123.5;
        state.ravenSideEndY = 456.25;
        state.ravenLiftTimer = 9;
        state.ravenLiftUsed = true;
        state.ravenPortentTimer = 210;
        state.ravenPortentOwnerIndex = 2;
        state.ravenPortentSerial = 7;
        state.ravenDecoyActive = true;
        state.ravenDecoyX = 333.0;
        state.ravenDecoyLifeFrames = 144;
        state.ravenDecoyUltimate = true;
        state.nullRockNeutralReuseTimer = 600;
        state.nullRockSideReuseTimer = 420;
        state.nullRockUpReuseTimer = 599;
        state.nullRockDownReuseTimer = 539;

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        state.write(new DataOutputStream(bos));

        LanBirdState decoded = LanBirdState.read(new DataInputStream(new ByteArrayInputStream(bos.toByteArray())));

        assertEquals(14, decoded.attackChargeFrames);
        assertEquals(5, decoded.pendingGroundAttackFrames);
        assertEquals(3, decoded.pendingGroundAttackVariantOrdinal);
        assertEquals(6, decoded.chargingAttackVariantOrdinal);
        assertEquals(10, decoded.activeAttackVariantOrdinal);
        assertEquals(2, decoded.dodgeTypeOrdinal);
        assertEquals(17, decoded.dodgeTimer);
        assertEquals(9, decoded.dodgeInvulnerabilityTimer);
        assertEquals(6, decoded.dodgeCooldown);
        assertEquals(-1, decoded.dodgeDirection);
        assertFalse(decoded.airDodgeAvailable);
        assertEquals(12, decoded.activeAerialLandingLagFrames);
        assertEquals(47, decoded.mockingbirdLoungeReuseTimer);
        assertEquals(31, decoded.phoenixLavaReuseTimer);
        assertEquals(13, decoded.phoenixFireballFizzleTimer);
        assertEquals(17, decoded.phoenixAirSideAimPoseTimer);
        assertEquals(45, decoded.phoenixAirSideLandingPrimeTimer);
        assertEquals(9, decoded.phoenixAirSideLandingFxTimer);
        assertEquals(74.5, decoded.roadrunnerMomentum);
        assertEquals(51, decoded.roadrunnerMomentumGraceTimer);
        assertTrue(decoded.roadrunnerBeepCharging);
        assertEquals(28, decoded.roadrunnerBeepChargeFrames);
        assertEquals(6, decoded.roadrunnerBeepMaxChargeHoldFrames);
        assertEquals(9, decoded.roadrunnerRicochetTimer);
        assertEquals(27.5, decoded.roadrunnerRicochetSpeed);
        assertTrue(decoded.roadrunnerDustDevilUsed);
        assertEquals(18, decoded.roadrunnerRoadBoostTimer);
        assertEquals(44, decoded.roadrunnerSlipTimer);
        assertEquals(-1, decoded.roadrunnerSlipDirection);
        assertEquals(73, decoded.roadrunnerRedlineTimer);
        assertEquals(8, decoded.roadrunnerRedlineRecoveryTimer);
        assertTrue(decoded.roadrunnerRedlineCinematic);
        assertEquals(-1, decoded.roadrunnerRedlineDirection);
        assertEquals(4, decoded.roadrunnerRedlineStrikeIndex);
        assertTrue(decoded.roadrunnerRedlineFinalResolved);
        assertEquals(101.25, decoded.roadrunnerRedlineStartX);
        assertEquals(202.5, decoded.roadrunnerRedlineStartY);
        assertEquals(303.75, decoded.roadrunnerRedlineEndX);
        assertEquals(404.0, decoded.roadrunnerRedlineEndY);
        assertEquals(505.25, decoded.roadrunnerRedlineAnchorX);
        assertEquals(606.5, decoded.roadrunnerRedlineAnchorY);
        assertEquals(707.75, decoded.roadrunnerRedlineLastStartX);
        assertEquals(808.0, decoded.roadrunnerRedlineLastStartY);
        assertEquals(909.25, decoded.roadrunnerRedlineLastEndX);
        assertEquals(1001.5, decoded.roadrunnerRedlineLastEndY);
        assertTrue(decoded.roadrunnerRedlineCaught[2]);
        assertEquals(14, decoded.grinchHeartSnatchTimer);
        assertTrue(decoded.grinchHeartSnatchUltimate);
        assertTrue(decoded.grinchHeartSnatchHit[1]);
        assertTrue(decoded.grinchSleighActive);
        assertTrue(decoded.grinchSleighRiding);
        assertEquals(88, decoded.grinchSleighTimer);
        assertEquals(-1, decoded.grinchSleighDirection);
        assertEquals(333.25, decoded.grinchSleighX);
        assertEquals(444.5, decoded.grinchSleighY);
        assertTrue(decoded.grinchSleighUltimate);
        assertTrue(decoded.grinchSleighHit[2]);
        assertEquals(11, decoded.grinchChimneyFlapTimer);
        assertTrue(decoded.grinchChimneyFlapUltimate);
        assertTrue(decoded.grinchUpSpecialUsed);
        assertTrue(decoded.grinchChimneyFlapHit[3]);
        assertTrue(decoded.grinchPresentActive);
        assertEquals(555.75, decoded.grinchPresentX);
        assertEquals(666.25, decoded.grinchPresentY);
        assertTrue(decoded.grinchPresentUltimate);
        assertEquals(19, decoded.grinchPresentAgeFrames);
        assertEquals(77, decoded.grinchPresentFuseFrames);
        assertEquals(123, decoded.grinchGiftstormTimer);
        assertEquals(4, decoded.grinchGiftstormDropIndex);
        assertTrue(decoded.grinchGiftstormFinalResolved);
        assertEquals(-1, decoded.grinchGiftstormDirection);
        assertEquals(701.25, decoded.grinchGiftstormSleighX);
        assertEquals(202.5, decoded.grinchGiftstormSleighY);
        assertEquals(111.25, decoded.grinchGiftstormFinalStartX);
        assertEquals(222.5, decoded.grinchGiftstormFinalStartY);
        assertEquals(333.75, decoded.grinchGiftstormFinalEndX);
        assertEquals(444.0, decoded.grinchGiftstormFinalEndY);
        assertEquals(555.25, decoded.grinchGiftstormLastDropX);
        assertEquals(666.5, decoded.grinchGiftstormLastDropY);
        assertEquals(2, decoded.grinchGiftstormLastDropKind);
        assertEquals(18, decoded.grinchGiftstormDropFxTimer);
        assertTrue(decoded.grinchGiftstormFinalHit[1]);
        assertEquals(44, decoded.carrionSwarmTimer);
        assertEquals(99, decoded.vultureBlackSkyTimer);
        assertEquals(7, decoded.vultureBlackSkySpawnTimer);
        assertEquals(31, decoded.vultureBlackSkyCrowsSpawned);
        assertEquals(5, decoded.vultureBlackSkyWaveIndex);
        assertTrue(decoded.vultureBlackSkyFinalHit);
        assertTrue(decoded.vultureBlackSkyHit[3]);
        assertTrue(decoded.isAshenSovereignSkin);
        assertTrue(decoded.penguinBellyCharging);
        assertEquals(41, decoded.penguinBellyChargeFrames);
        assertEquals(13, decoded.penguinBellySlideTimer);
        assertEquals(-1, decoded.penguinBellyDirection);
        assertEquals(21, decoded.penguinRocketTimer);
        assertTrue(decoded.penguinUpSpecialUsed);
        assertTrue(decoded.penguinSnowFortActive);
        assertEquals(1234.5, decoded.penguinSnowFortX);
        assertEquals(2100.25, decoded.penguinSnowFortY);
        assertEquals(33, decoded.penguinSnowFortHealth);
        assertEquals(19, decoded.shoebillThrustTimer);
        assertEquals(-1, decoded.shoebillThrustDirection);
        assertEquals(12, decoded.shoebillMarshLiftTimer);
        assertTrue(decoded.shoebillUpSpecialUsed);
        assertTrue(decoded.shoebillStatueCountered);
        assertEquals(7, decoded.shoebillCounterBurstTimer);
        assertEquals(88, decoded.shoebillFinalStillnessTimer);
        assertEquals(2, decoded.shoebillFinalStillnessTargetIndex);
        assertEquals(600.25, decoded.shoebillFinalStillnessStatueX);
        assertEquals(1200.5, decoded.shoebillFinalStillnessStatueY);
        assertEquals(610.75, decoded.shoebillFinalStillnessBeamStartX);
        assertEquals(930.25, decoded.shoebillFinalStillnessBeamStartY);
        assertEquals(720.5, decoded.shoebillFinalStillnessBeamTargetX);
        assertEquals(880.75, decoded.shoebillFinalStillnessBeamTargetY);
        assertTrue(decoded.shoebillFinalStillnessBeamResolved);
        assertEquals(91, decoded.turkeyHarvestTribunalTimer);
        assertEquals(555.25, decoded.turkeyHarvestTribunalX);
        assertEquals(777.5, decoded.turkeyHarvestTribunalY);
        assertTrue(decoded.turkeyHarvestTribunalFinalResolved);
        assertTrue(decoded.turkeyHarvestTribunalFinalHit[2]);
        assertEquals(77, decoded.hummingFrenzyTimer);
        assertEquals(1, decoded.hummingFrenzyTargetIndex);
        assertEquals(2, decoded.hummingFrenzyStrikeIndex);
        assertEquals(2, decoded.hummingFrenzyConnectedStrikes);
        assertTrue(decoded.hummingFrenzyFinalResolved);
        assertEquals(101.25, decoded.hummingFrenzyAnchorX);
        assertEquals(202.5, decoded.hummingFrenzyAnchorY);
        assertEquals(303.75, decoded.hummingFrenzyTargetX);
        assertEquals(404.0, decoded.hummingFrenzyTargetY);
        assertEquals(505.25, decoded.hummingFrenzyLastStartX);
        assertEquals(606.5, decoded.hummingFrenzyLastStartY);
        assertEquals(707.75, decoded.hummingFrenzyLastEndX);
        assertEquals(808.0, decoded.hummingFrenzyLastEndY);
        assertEquals(6, decoded.hummingFrenzyHitCooldown[2]);
        assertEquals(63.5, decoded.opiumResourceMeter);
        assertTrue(decoded.opiumNeutralFueled);
        assertEquals(29, decoded.opiumNeutralReuseTimer);
        assertEquals(11, decoded.opiumSideTimer);
        assertTrue(decoded.opiumSideFueled);
        assertTrue(decoded.opiumSideHit[1]);
        assertEquals(8, decoded.opiumUpTimer);
        assertTrue(decoded.opiumUpSpecialUsed);
        assertTrue(decoded.opiumUpFueled);
        assertEquals(33, decoded.opiumDownReuseTimer);
        assertEquals(210, decoded.opiumUltimateTimer);
        assertTrue(decoded.opiumUltimateCollapsePending);
        assertEquals(432.25, decoded.opiumUltimateCloudX);
        assertEquals(876.5, decoded.opiumUltimateCloudY);
        assertEquals(144, decoded.heisenUltimateTimer);
        assertTrue(decoded.heisenUltimateShatterPending);
        assertEquals(25, decoded.heisenUltimateVolleyTimer);
        assertEquals(222.5, decoded.heisenUltimateVolleyOriginX);
        assertEquals(333.5, decoded.heisenUltimateVolleyOriginY);
        assertEquals(444.5, decoded.heisenUltimateVolleyTargetX);
        assertEquals(555.5, decoded.heisenUltimateVolleyTargetY);
        assertTrue(decoded.heisenUltimateVolleyHit);
        assertEquals(66, decoded.opiumDrowsyTimer);
        assertEquals(2, decoded.opiumDrowsyOwnerIndex);
        assertTrue(decoded.opiumDrowsyUltimate);
        assertEquals(88, decoded.heisenBrittleTimer);
        assertEquals(3, decoded.heisenBrittleOwnerIndex);
        assertTrue(decoded.heisenBrittleUltimate);
        assertTrue(decoded.pigeonCoronationActive);
        assertEquals(77, decoded.pigeonCoronationTimer);
        assertEquals(111.25, decoded.pigeonCoronationX);
        assertEquals(222.5, decoded.pigeonCoronationY);
        assertFalse(decoded.pigeonCoronationFinalResolved);
        assertTrue(decoded.pigeonCoronationStayedInside);
        assertEquals(12, decoded.pigeonCoronationTickCooldown[3]);
        assertTrue(decoded.pigeonCoronationFinalHit[0]);
        assertEquals(71, decoded.pigeonScavengeTimer);
        assertEquals(29, decoded.pigeonScavengeHoldFrames);
        assertTrue(decoded.pigeonScavengeAirborne);
        assertEquals(6, decoded.pigeonScavengeHitCooldown[2]);
        assertTrue(decoded.eagleSkySovereignActive);
        assertFalse(decoded.eagleSkySovereignDiving);
        assertEquals(44, decoded.eagleSkySovereignTimer);
        assertEquals(555.25, decoded.eagleSkySovereignTargetX);
        assertEquals(666.5, decoded.eagleSkySovereignTargetY);
        assertEquals(77.75, decoded.eagleSkySovereignDiveStartY);
        assertTrue(decoded.eagleSkySovereignHitResolved);
        assertTrue(decoded.eagleSkySovereignHit[2]);
        assertTrue(decoded.falconTerminalVelocityActive);
        assertTrue(decoded.falconTerminalVelocityStriking);
        assertFalse(decoded.falconTerminalVelocityHitAny);
        assertEquals(5, decoded.falconTerminalVelocityTimer);
        assertEquals(-1, decoded.falconTerminalVelocityDirection);
        assertEquals(910.25, decoded.falconTerminalVelocityStartX);
        assertEquals(303.5, decoded.falconTerminalVelocityStartY);
        assertEquals(401.75, decoded.falconTerminalVelocityEndX);
        assertEquals(700.5, decoded.falconTerminalVelocityEndY);
        assertTrue(decoded.falconTerminalVelocityHit[1]);
        assertEquals(97, decoded.razorbillGuillotineTimer);
        assertEquals(4, decoded.razorbillGuillotineSlashIndex);
        assertEquals(66, decoded.razorbillGuillotineWakeTimer);
        assertTrue(decoded.razorbillGuillotineFinalResolved);
        assertEquals(118.25, decoded.razorbillGuillotineAnchorX);
        assertEquals(228.5, decoded.razorbillGuillotineAnchorY);
        assertEquals(338.75, decoded.razorbillGuillotineTargetX);
        assertEquals(448.0, decoded.razorbillGuillotineTargetY);
        assertEquals(558.25, decoded.razorbillGuillotineLastStartX);
        assertEquals(668.5, decoded.razorbillGuillotineLastStartY);
        assertEquals(778.75, decoded.razorbillGuillotineLastEndX);
        assertEquals(888.0, decoded.razorbillGuillotineLastEndY);
        assertEquals(128.5, decoded.razorbillGuillotineWakeX1);
        assertEquals(488.25, decoded.razorbillGuillotineWakeX2);
        assertEquals(918.75, decoded.razorbillGuillotineWakeY);
        assertEquals(6, decoded.razorbillGuillotineHitCooldown[0]);
        assertEquals(14, decoded.razorbillGuillotineWakeHitCooldown[2]);
        assertEquals(2, decoded.pelicanCargoCount);
        assertEquals(8, decoded.pelicanNeutralTimer);
        assertEquals(12, decoded.pelicanNeutralReuseTimer);
        assertTrue(decoded.pelicanNeutralUltimate);
        assertTrue(decoded.pelicanNeutralHit[1]);
        assertEquals(14, decoded.pelicanSideTimer);
        assertEquals(21, decoded.pelicanSideReuseTimer);
        assertEquals(-1, decoded.pelicanSideDirection);
        assertEquals(2, decoded.pelicanSideCargoSpent);
        assertTrue(decoded.pelicanSideUltimate);
        assertTrue(decoded.pelicanSideHit[2]);
        assertEquals(17, decoded.pelicanUpTimer);
        assertTrue(decoded.pelicanUpSpecialUsed);
        assertTrue(decoded.pelicanUpUltimate);
        assertTrue(decoded.pelicanKeelDiveActive);
        assertTrue(decoded.pelicanUpHit[3]);
        assertTrue(decoded.pelicanDownCharging);
        assertEquals(19, decoded.pelicanDownHoldFrames);
        assertEquals(25, decoded.pelicanDownReuseTimer);
        assertTrue(decoded.pelicanDownUltimate);
        assertEquals(9, decoded.pelicanBilgeFxTimer);
        assertEquals(2, decoded.pelicanBilgeCargoSpent);
        assertTrue(decoded.pelicanBilgeUltimate);
        assertEquals(144, decoded.pelicanFullHoldTimer);
        assertEquals(88, decoded.pelicanMaelstromTimer);
        assertEquals(5, decoded.pelicanMaelstromPulseCooldown);
        assertTrue(decoded.pelicanMaelstromFinalResolved);
        assertEquals(2, decoded.pelicanMaelstromCargoSpent);
        assertEquals(1234.5, decoded.pelicanMaelstromX);
        assertEquals(2222.25, decoded.pelicanMaelstromY);
        assertEquals(33, decoded.pelicanMaelstromGeyserFxTimer);
        assertTrue(decoded.pelicanMaelstromFinalHit[2]);
        assertEquals(17, decoded.batNeutralReuseTimer);
        assertEquals(9, decoded.batWingcutTimer);
        assertEquals(-1, decoded.batWingcutDirection);
        assertTrue(decoded.batWingcutFromHang);
        assertTrue(decoded.batWingcutHit[2]);
        assertTrue(decoded.batMoonriseUsed);
        assertEquals(12, decoded.batSilentDiveTimer);
        assertTrue(decoded.batSilentFromHang);
        assertTrue(decoded.batSilentHit[1]);
        assertEquals(144, decoded.batCathedralTimer);
        assertEquals(777.25, decoded.batEchoFxEndX);
        assertTrue(decoded.batEchoFxBounced);
        assertTrue(decoded.ravenQuillCharging);
        assertEquals(18, decoded.ravenQuillChargeFrames);
        assertEquals(22, decoded.ravenNeutralReuseTimer);
        assertEquals(11, decoded.ravenSideTimer);
        assertEquals(-1, decoded.ravenSideDirection);
        assertTrue(decoded.ravenSideEmpowered);
        assertEquals(123.5, decoded.ravenSideStartX);
        assertEquals(456.25, decoded.ravenSideEndY);
        assertEquals(9, decoded.ravenLiftTimer);
        assertTrue(decoded.ravenLiftUsed);
        assertEquals(210, decoded.ravenPortentTimer);
        assertEquals(2, decoded.ravenPortentOwnerIndex);
        assertEquals(7, decoded.ravenPortentSerial);
        assertTrue(decoded.ravenDecoyActive);
        assertEquals(333.0, decoded.ravenDecoyX);
        assertEquals(144, decoded.ravenDecoyLifeFrames);
        assertTrue(decoded.ravenDecoyUltimate);
        assertEquals(600, decoded.nullRockNeutralReuseTimer);
        assertEquals(420, decoded.nullRockSideReuseTimer);
        assertEquals(599, decoded.nullRockUpReuseTimer);
        assertEquals(539, decoded.nullRockDownReuseTimer);
    }
}
