package com.example.birdgame3;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class LanProtocolTest {
    @Test
    void framedPayloadRoundTrips() throws IOException {
        byte[] payload = LanProtocol.buildMessage(LanProtocol.MSG_READY, out -> out.writeBoolean(true));

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        LanProtocol.writeFramed(new DataOutputStream(bos), payload);

        byte[] read = LanProtocol.readFramed(new DataInputStream(new ByteArrayInputStream(bos.toByteArray())));
        assertArrayEquals(payload, read);

        DataInputStream in = new DataInputStream(new ByteArrayInputStream(read));
        assertEquals(LanProtocol.MSG_READY, in.readByte());
        assertTrue(in.readBoolean());
    }

    @Test
    void invalidFrameLengthIsRejected() throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        DataOutputStream out = new DataOutputStream(bos);
        out.writeInt(5_000_001);
        out.flush();

        DataInputStream in = new DataInputStream(new ByteArrayInputStream(bos.toByteArray()));
        assertThrows(IOException.class, () -> LanProtocol.readFramed(in));
    }

    @Test
    void lanBirdStateRoundTripsDodgeFields() throws IOException {
        LanBirdState state = new LanBirdState();
        state.attackChargeFrames = 14;
        state.pendingGroundAttackFrames = 5;
        state.pendingGroundAttackVariantOrdinal = 3;
        state.chargingAttackVariantOrdinal = 6;
        state.activeAttackVariantOrdinal = 10;
        state.dodgeTypeOrdinal = 2;
        state.dodgeTimer = 17;
        state.dodgeInvulnerabilityTimer = 9;
        state.dodgeCooldown = 6;
        state.dodgeDirection = -1;
        state.airDodgeAvailable = false;
        state.activeAerialLandingLagFrames = 12;
        state.phoenixLavaReuseTimer = 31;
        state.roadrunnerMomentum = 74.5;
        state.roadrunnerBeepCharging = true;
        state.roadrunnerBeepChargeFrames = 28;
        state.roadrunnerBeepMaxChargeHoldFrames = 6;
        state.roadrunnerRicochetTimer = 9;
        state.roadrunnerRicochetSpeed = 27.5;
        state.roadrunnerDustDevilUsed = true;
        state.roadrunnerRoadBoostTimer = 18;
        state.roadrunnerSlipTimer = 44;
        state.roadrunnerSlipDirection = -1;
        state.penguinBellyCharging = true;
        state.penguinBellyChargeFrames = 41;
        state.penguinBellySlideTimer = 13;
        state.penguinBellyDirection = -1;
        state.penguinRocketTimer = 21;
        state.penguinUpSpecialUsed = true;
        state.penguinSnowFortActive = true;
        state.penguinSnowFortX = 1234.5;
        state.penguinSnowFortY = 2100.25;
        state.penguinSnowFortHealth = 33;
        state.shoebillThrustTimer = 19;
        state.shoebillThrustDirection = -1;
        state.shoebillMarshLiftTimer = 12;
        state.shoebillUpSpecialUsed = true;
        state.shoebillStatueCountered = true;
        state.shoebillCounterBurstTimer = 7;
        state.opiumResourceMeter = 63.5;
        state.opiumNeutralFueled = true;
        state.opiumNeutralReuseTimer = 29;
        state.opiumSideTimer = 11;
        state.opiumSideFueled = true;
        state.opiumSideHit[1] = true;
        state.opiumUpTimer = 8;
        state.opiumUpSpecialUsed = true;
        state.opiumUpFueled = true;
        state.opiumDownReuseTimer = 33;
        state.opiumUltimateTimer = 210;
        state.opiumUltimateCollapsePending = true;
        state.opiumUltimateCloudX = 432.25;
        state.opiumUltimateCloudY = 876.5;
        state.heisenUltimateTimer = 144;
        state.heisenUltimateShatterPending = true;
        state.heisenUltimateVolleyTimer = 25;
        state.heisenUltimateVolleyOriginX = 222.5;
        state.heisenUltimateVolleyOriginY = 333.5;
        state.heisenUltimateVolleyTargetX = 444.5;
        state.heisenUltimateVolleyTargetY = 555.5;
        state.heisenUltimateVolleyHit = true;
        state.opiumDrowsyTimer = 66;
        state.opiumDrowsyOwnerIndex = 2;
        state.opiumDrowsyUltimate = true;
        state.heisenBrittleTimer = 88;
        state.heisenBrittleOwnerIndex = 3;
        state.heisenBrittleUltimate = true;
        state.pelicanCargoCount = 2;
        state.pelicanNeutralTimer = 8;
        state.pelicanNeutralReuseTimer = 12;
        state.pelicanNeutralUltimate = true;
        state.pelicanNeutralHit[1] = true;
        state.pelicanSideTimer = 14;
        state.pelicanSideReuseTimer = 21;
        state.pelicanSideDirection = -1;
        state.pelicanSideCargoSpent = 2;
        state.pelicanSideUltimate = true;
        state.pelicanSideHit[2] = true;
        state.pelicanUpTimer = 17;
        state.pelicanUpSpecialUsed = true;
        state.pelicanUpUltimate = true;
        state.pelicanKeelDiveActive = true;
        state.pelicanUpHit[3] = true;
        state.pelicanDownCharging = true;
        state.pelicanDownHoldFrames = 19;
        state.pelicanDownReuseTimer = 25;
        state.pelicanDownUltimate = true;
        state.pelicanBilgeFxTimer = 9;
        state.pelicanBilgeCargoSpent = 2;
        state.pelicanBilgeUltimate = true;
        state.pelicanFullHoldTimer = 144;
        state.batNeutralReuseTimer = 17;
        state.batWingcutTimer = 9;
        state.batWingcutDirection = -1;
        state.batWingcutFromHang = true;
        state.batWingcutHit[2] = true;
        state.batMoonriseUsed = true;
        state.batSilentDiveTimer = 12;
        state.batSilentFromHang = true;
        state.batSilentHit[1] = true;
        state.batCathedralTimer = 144;
        state.batEchoFxEndX = 777.25;
        state.batEchoFxBounced = true;

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        state.write(new DataOutputStream(bos));

        LanBirdState decoded = LanBirdState.read(new DataInputStream(new ByteArrayInputStream(bos.toByteArray())));

        assertEquals(14, decoded.attackChargeFrames);
        assertEquals(5, decoded.pendingGroundAttackFrames);
        assertEquals(3, decoded.pendingGroundAttackVariantOrdinal);
        assertEquals(6, decoded.chargingAttackVariantOrdinal);
        assertEquals(10, decoded.activeAttackVariantOrdinal);
        assertEquals(2, decoded.dodgeTypeOrdinal);
        assertEquals(17, decoded.dodgeTimer);
        assertEquals(9, decoded.dodgeInvulnerabilityTimer);
        assertEquals(6, decoded.dodgeCooldown);
        assertEquals(-1, decoded.dodgeDirection);
        assertFalse(decoded.airDodgeAvailable);
        assertEquals(12, decoded.activeAerialLandingLagFrames);
        assertEquals(31, decoded.phoenixLavaReuseTimer);
        assertEquals(74.5, decoded.roadrunnerMomentum);
        assertTrue(decoded.roadrunnerBeepCharging);
        assertEquals(28, decoded.roadrunnerBeepChargeFrames);
        assertEquals(6, decoded.roadrunnerBeepMaxChargeHoldFrames);
        assertEquals(9, decoded.roadrunnerRicochetTimer);
        assertEquals(27.5, decoded.roadrunnerRicochetSpeed);
        assertTrue(decoded.roadrunnerDustDevilUsed);
        assertEquals(18, decoded.roadrunnerRoadBoostTimer);
        assertEquals(44, decoded.roadrunnerSlipTimer);
        assertEquals(-1, decoded.roadrunnerSlipDirection);
        assertTrue(decoded.penguinBellyCharging);
        assertEquals(41, decoded.penguinBellyChargeFrames);
        assertEquals(13, decoded.penguinBellySlideTimer);
        assertEquals(-1, decoded.penguinBellyDirection);
        assertEquals(21, decoded.penguinRocketTimer);
        assertTrue(decoded.penguinUpSpecialUsed);
        assertTrue(decoded.penguinSnowFortActive);
        assertEquals(1234.5, decoded.penguinSnowFortX);
        assertEquals(2100.25, decoded.penguinSnowFortY);
        assertEquals(33, decoded.penguinSnowFortHealth);
        assertEquals(19, decoded.shoebillThrustTimer);
        assertEquals(-1, decoded.shoebillThrustDirection);
        assertEquals(12, decoded.shoebillMarshLiftTimer);
        assertTrue(decoded.shoebillUpSpecialUsed);
        assertTrue(decoded.shoebillStatueCountered);
        assertEquals(7, decoded.shoebillCounterBurstTimer);
        assertEquals(63.5, decoded.opiumResourceMeter);
        assertTrue(decoded.opiumNeutralFueled);
        assertEquals(29, decoded.opiumNeutralReuseTimer);
        assertEquals(11, decoded.opiumSideTimer);
        assertTrue(decoded.opiumSideFueled);
        assertTrue(decoded.opiumSideHit[1]);
        assertEquals(8, decoded.opiumUpTimer);
        assertTrue(decoded.opiumUpSpecialUsed);
        assertTrue(decoded.opiumUpFueled);
        assertEquals(33, decoded.opiumDownReuseTimer);
        assertEquals(210, decoded.opiumUltimateTimer);
        assertTrue(decoded.opiumUltimateCollapsePending);
        assertEquals(432.25, decoded.opiumUltimateCloudX);
        assertEquals(876.5, decoded.opiumUltimateCloudY);
        assertEquals(144, decoded.heisenUltimateTimer);
        assertTrue(decoded.heisenUltimateShatterPending);
        assertEquals(25, decoded.heisenUltimateVolleyTimer);
        assertEquals(222.5, decoded.heisenUltimateVolleyOriginX);
        assertEquals(333.5, decoded.heisenUltimateVolleyOriginY);
        assertEquals(444.5, decoded.heisenUltimateVolleyTargetX);
        assertEquals(555.5, decoded.heisenUltimateVolleyTargetY);
        assertTrue(decoded.heisenUltimateVolleyHit);
        assertEquals(66, decoded.opiumDrowsyTimer);
        assertEquals(2, decoded.opiumDrowsyOwnerIndex);
        assertTrue(decoded.opiumDrowsyUltimate);
        assertEquals(88, decoded.heisenBrittleTimer);
        assertEquals(3, decoded.heisenBrittleOwnerIndex);
        assertTrue(decoded.heisenBrittleUltimate);
        assertEquals(2, decoded.pelicanCargoCount);
        assertEquals(8, decoded.pelicanNeutralTimer);
        assertEquals(12, decoded.pelicanNeutralReuseTimer);
        assertTrue(decoded.pelicanNeutralUltimate);
        assertTrue(decoded.pelicanNeutralHit[1]);
        assertEquals(14, decoded.pelicanSideTimer);
        assertEquals(21, decoded.pelicanSideReuseTimer);
        assertEquals(-1, decoded.pelicanSideDirection);
        assertEquals(2, decoded.pelicanSideCargoSpent);
        assertTrue(decoded.pelicanSideUltimate);
        assertTrue(decoded.pelicanSideHit[2]);
        assertEquals(17, decoded.pelicanUpTimer);
        assertTrue(decoded.pelicanUpSpecialUsed);
        assertTrue(decoded.pelicanUpUltimate);
        assertTrue(decoded.pelicanKeelDiveActive);
        assertTrue(decoded.pelicanUpHit[3]);
        assertTrue(decoded.pelicanDownCharging);
        assertEquals(19, decoded.pelicanDownHoldFrames);
        assertEquals(25, decoded.pelicanDownReuseTimer);
        assertTrue(decoded.pelicanDownUltimate);
        assertEquals(9, decoded.pelicanBilgeFxTimer);
        assertEquals(2, decoded.pelicanBilgeCargoSpent);
        assertTrue(decoded.pelicanBilgeUltimate);
        assertEquals(144, decoded.pelicanFullHoldTimer);
        assertEquals(17, decoded.batNeutralReuseTimer);
        assertEquals(9, decoded.batWingcutTimer);
        assertEquals(-1, decoded.batWingcutDirection);
        assertTrue(decoded.batWingcutFromHang);
        assertTrue(decoded.batWingcutHit[2]);
        assertTrue(decoded.batMoonriseUsed);
        assertEquals(12, decoded.batSilentDiveTimer);
        assertTrue(decoded.batSilentFromHang);
        assertTrue(decoded.batSilentHit[1]);
        assertEquals(144, decoded.batCathedralTimer);
        assertEquals(777.25, decoded.batEchoFxEndX);
        assertTrue(decoded.batEchoFxBounced);
    }
}
