package com.example.birdgame3;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LanStateTest {
    @Test
    void writeReadRoundTripPreservesNestedState() throws IOException {
        LanState state = new LanState();
        state.matchTimer = 321;
        state.matchEnded = true;
        state.suddenDeathActive = true;
        state.suddenDeathSmashStyle = true;
        state.activePlayers = 3;
        state.camX = 150.5;
        state.camY = -20.25;
        state.zoom = 0.8;
        state.shakeIntensity = 2.75;
        state.hitstopFrames = 4;
        state.scores = new int[]{10, 20, 30, 40};
        state.killFeed = List.of("P1 KO", "P2 KO");

        LanBirdState bird = new LanBirdState();
        bird.typeOrdinal = 2;
        bird.x = 12.5;
        bird.y = 50.25;
        bird.health = 133.0;
        bird.facingRight = true;
        bird.specialCooldown = 18;
        bird.aerialAttackActive = true;
        bird.aerialAttackTotalFrames = 12;
        bird.landingLagTimer = 5;
        bird.isCitySkin = true;
        bird.jumpSquatTimer = 2;
        bird.shortHopQueued = true;
        bird.isBlocking = true;
        bird.blockCooldown = 11;
        bird.shieldHealth = 37.5;
        bird.shieldStunFrames = 8;
        bird.parryWindowFrames = 2;
        bird.shieldHoldVisual = 0.65;
        bird.techBufferTimer = 4;
        bird.knockdownTimer = 22;
        bird.razorbillStormTimer = 9;
        bird.razorbillStormHoldFrames = 31;
        bird.razorbillStormReuseTimer = 17;
        bird.razorbillStormUltimate = true;
        bird.razorbillStormReleased = true;
        bird.razorbillStormHitCooldown[2] = 6;
        bird.razorbillSideReuseTimer = 19;
        bird.razorbillSideSpecialUsed = true;
        bird.razorbillSideUltimate = true;
        bird.razorbillShearTimer = 11;
        bird.razorbillShearDirection = 1;
        bird.razorbillShearUltimate = true;
        bird.razorbillUpSpecialUsed = true;
        bird.razorbillCounterTimer = 7;
        bird.razorbillCounterReuseTimer = 23;
        bird.razorbillCounterWhiffTimer = 5;
        bird.razorbillCounterBurstTimer = 4;
        bird.razorbillCounterUltimate = true;
        bird.razorbillCountered = true;
        bird.razorbillCounterAttemptActive = true;
        bird.razorbillGuillotineTimer = 97;
        bird.razorbillGuillotineSlashIndex = 3;
        bird.razorbillGuillotineWakeTimer = 88;
        bird.razorbillGuillotineFinalResolved = true;
        bird.razorbillGuillotineAnchorX = 111.25;
        bird.razorbillGuillotineAnchorY = 222.5;
        bird.razorbillGuillotineTargetX = 333.75;
        bird.razorbillGuillotineTargetY = 444.0;
        bird.razorbillGuillotineLastStartX = 555.25;
        bird.razorbillGuillotineLastStartY = 666.5;
        bird.razorbillGuillotineLastEndX = 777.75;
        bird.razorbillGuillotineLastEndY = 888.0;
        bird.razorbillGuillotineWakeX1 = 120.5;
        bird.razorbillGuillotineWakeX2 = 480.25;
        bird.razorbillGuillotineWakeY = 910.75;
        bird.razorbillGuillotineHitCooldown[1] = 5;
        bird.razorbillGuillotineWakeHitCooldown[3] = 13;
        bird.pelicanCargoCount = 2;
        bird.pelicanNeutralTimer = 8;
        bird.pelicanNeutralReuseTimer = 12;
        bird.pelicanNeutralUltimate = true;
        bird.pelicanNeutralHit[1] = true;
        bird.pelicanSideTimer = 14;
        bird.pelicanSideReuseTimer = 21;
        bird.pelicanSideDirection = -1;
        bird.pelicanSideCargoSpent = 2;
        bird.pelicanSideUltimate = true;
        bird.pelicanSideHit[2] = true;
        bird.pelicanUpTimer = 17;
        bird.pelicanUpSpecialUsed = true;
        bird.pelicanUpUltimate = true;
        bird.pelicanKeelDiveActive = true;
        bird.pelicanUpHit[3] = true;
        bird.pelicanDownCharging = true;
        bird.pelicanDownHoldFrames = 19;
        bird.pelicanDownReuseTimer = 25;
        bird.pelicanDownUltimate = true;
        bird.pelicanBilgeFxTimer = 9;
        bird.pelicanBilgeCargoSpent = 2;
        bird.pelicanBilgeUltimate = true;
        bird.pelicanFullHoldTimer = 144;
        bird.pelicanMaelstromTimer = 88;
        bird.pelicanMaelstromPulseCooldown = 5;
        bird.pelicanMaelstromFinalResolved = true;
        bird.pelicanMaelstromCargoSpent = 2;
        bird.pelicanMaelstromX = 1234.5;
        bird.pelicanMaelstromY = 2222.25;
        bird.pelicanMaelstromGeyserFxTimer = 33;
        bird.pelicanMaelstromFinalHit[2] = true;
        bird.batWingcutTimer = 13;
        bird.batWingcutFromHang = true;
        bird.batMoonriseUsed = true;
        bird.batSilentFromHang = true;
        bird.batCathedralTimer = 77;
        bird.pigeonCoronationActive = true;
        bird.pigeonCoronationTimer = 123;
        bird.pigeonCoronationX = 456.5;
        bird.pigeonCoronationY = 789.25;
        bird.pigeonCoronationFinalResolved = true;
        bird.pigeonCoronationStayedInside = false;
        bird.pigeonCoronationTickCooldown[2] = 17;
        bird.pigeonCoronationFinalHit[1] = true;
        bird.pigeonFeatherCharging = true;
        bird.pigeonFeatherChargeFrames = 41;
        bird.pigeonFeatherBurstChargeFrames = 23;
        bird.pigeonScavengeTimer = 64;
        bird.pigeonScavengeHoldFrames = 36;
        bird.pigeonScavengeAirborne = true;
        bird.pigeonScavengeHitCooldown[3] = 8;
        bird.raptorEggCharging = true;
        bird.raptorEggChargeFrames = 31;
        bird.raptorEggDirection = -1;
        bird.raptorEggActive[2] = true;
        bird.raptorEggX[2] = 345.25;
        bird.raptorEggY[2] = 456.5;
        bird.raptorEggVX[2] = -15.75;
        bird.raptorEggVY[2] = 1.25;
        bird.raptorEggPower[2] = 0.75;
        bird.raptorEggLife[2] = 52;
        bird.raptorRushCharging = true;
        bird.raptorRushChargeFrames = 22;
        bird.raptorRushChargeRatio = 0.625;
        bird.eagleSkySovereignActive = true;
        bird.eagleSkySovereignDiving = true;
        bird.eagleSkySovereignTimer = 19;
        bird.eagleSkySovereignTargetX = 321.5;
        bird.eagleSkySovereignTargetY = 654.25;
        bird.eagleSkySovereignDiveStartY = 88.75;
        bird.eagleSkySovereignHitResolved = false;
        bird.eagleSkySovereignHit[3] = true;
        bird.falconTerminalVelocityActive = true;
        bird.falconTerminalVelocityStriking = true;
        bird.falconTerminalVelocityHitAny = true;
        bird.falconTerminalVelocityTimer = 6;
        bird.falconTerminalVelocityDirection = -1;
        bird.falconTerminalVelocityStartX = 701.5;
        bird.falconTerminalVelocityStartY = 202.25;
        bird.falconTerminalVelocityEndX = 118.75;
        bird.falconTerminalVelocityEndY = 515.5;
        bird.falconTerminalVelocityHit[2] = true;
        bird.penguinAbsoluteZeroTimer = 77;
        bird.penguinAbsoluteZeroWaveIndex = 3;
        bird.penguinAbsoluteZeroThroneX = 432.25;
        bird.penguinAbsoluteZeroThroneY = 876.5;
        bird.shoebillFinalStillnessTimer = 88;
        bird.shoebillFinalStillnessTargetIndex = 2;
        bird.shoebillFinalStillnessStatueX = 600.25;
        bird.shoebillFinalStillnessStatueY = 1200.5;
        bird.shoebillFinalStillnessBeamStartX = 610.75;
        bird.shoebillFinalStillnessBeamStartY = 930.25;
        bird.shoebillFinalStillnessBeamTargetX = 720.5;
        bird.shoebillFinalStillnessBeamTargetY = 880.75;
        bird.shoebillFinalStillnessBeamResolved = true;
        bird.turkeyHarvestTribunalTimer = 91;
        bird.turkeyHarvestTribunalX = 555.25;
        bird.turkeyHarvestTribunalY = 777.5;
        bird.turkeyHarvestTribunalFinalResolved = true;
        bird.turkeyHarvestTribunalFinalHit[2] = true;
        bird.roadrunnerRedlineTimer = 73;
        bird.roadrunnerRedlineRecoveryTimer = 8;
        bird.roadrunnerRedlineCinematic = true;
        bird.roadrunnerRedlineDirection = -1;
        bird.roadrunnerRedlineStrikeIndex = 4;
        bird.roadrunnerRedlineFinalResolved = true;
        bird.roadrunnerRedlineStartX = 101.25;
        bird.roadrunnerRedlineStartY = 202.5;
        bird.roadrunnerRedlineEndX = 303.75;
        bird.roadrunnerRedlineEndY = 404.0;
        bird.roadrunnerRedlineAnchorX = 505.25;
        bird.roadrunnerRedlineAnchorY = 606.5;
        bird.roadrunnerRedlineLastStartX = 707.75;
        bird.roadrunnerRedlineLastStartY = 808.0;
        bird.roadrunnerRedlineLastEndX = 909.25;
        bird.roadrunnerRedlineLastEndY = 1001.5;
        bird.roadrunnerRedlineCaught[2] = true;
        bird.grinchSleighActive = true;
        bird.grinchSleighTimer = 88;
        bird.grinchSleighDirection = -1;
        bird.grinchSleighX = 333.25;
        bird.grinchSleighY = 444.5;
        bird.grinchPresentActive = true;
        bird.grinchPresentX = 555.75;
        bird.grinchPresentY = 666.25;
        bird.grinchPresentUltimate = true;
        bird.grinchPresentAgeFrames = 19;
        bird.grinchPresentFuseFrames = 77;
        bird.grinchGiftstormTimer = 123;
        bird.grinchGiftstormDropIndex = 4;
        bird.grinchGiftstormFinalResolved = true;
        bird.grinchGiftstormDirection = -1;
        bird.grinchGiftstormSleighX = 701.25;
        bird.grinchGiftstormSleighY = 202.5;
        bird.grinchGiftstormFinalStartX = 111.25;
        bird.grinchGiftstormFinalStartY = 222.5;
        bird.grinchGiftstormFinalEndX = 333.75;
        bird.grinchGiftstormFinalEndY = 444.0;
        bird.grinchGiftstormLastDropKind = 2;
        bird.grinchGiftstormDropFxTimer = 18;
        bird.grinchGiftstormFinalHit[1] = true;
        bird.carrionSwarmTimer = 44;
        bird.vultureBlackSkyTimer = 99;
        bird.vultureBlackSkySpawnTimer = 7;
        bird.vultureBlackSkyCrowsSpawned = 31;
        bird.vultureBlackSkyWaveIndex = 5;
        bird.vultureBlackSkyFinalHit = true;
        bird.vultureBlackSkyHit[3] = true;
        bird.hummingFrenzyTimer = 66;
        bird.hummingFrenzyTargetIndex = 1;
        bird.hummingFrenzyStrikeIndex = 3;
        bird.hummingFrenzyConnectedStrikes = 2;
        bird.hummingFrenzyFinalResolved = true;
        bird.hummingFrenzyAnchorX = 121.25;
        bird.hummingFrenzyAnchorY = 242.5;
        bird.hummingFrenzyTargetX = 363.75;
        bird.hummingFrenzyTargetY = 484.0;
        bird.hummingFrenzyLastStartX = 605.25;
        bird.hummingFrenzyLastStartY = 726.5;
        bird.hummingFrenzyLastEndX = 847.75;
        bird.hummingFrenzyLastEndY = 968.0;
        bird.hummingFrenzyHitCooldown[1] = 5;
        bird.ultimateMeter = 44.0;
        state.birds[0] = bird;

        LanState.PowerUpState powerUp = new LanState.PowerUpState();
        powerUp.x = 200.0;
        powerUp.y = 300.0;
        powerUp.typeOrdinal = 1;
        state.powerUps.add(powerUp);

        LanState.NectarNodeState nectar = new LanState.NectarNodeState();
        nectar.x = 10.0;
        nectar.y = 20.0;
        nectar.isSpeed = true;
        nectar.active = false;
        state.nectarNodes.add(nectar);

        LanState.SwingingVineState vine = new LanState.SwingingVineState();
        vine.baseX = 11.0;
        vine.baseY = 22.0;
        vine.length = 33.0;
        vine.angle = 0.5;
        vine.angularVelocity = 0.75;
        state.swingingVines.add(vine);

        LanState.WindVentState vent = new LanState.WindVentState();
        vent.x = 1.0;
        vent.y = 2.0;
        vent.w = 3.0;
        vent.cooldown = 4;
        state.windVents.add(vent);

        LanState.CrowMinionState crow = new LanState.CrowMinionState();
        crow.x = 7.0;
        crow.y = 8.0;
        crow.age = 9;
        crow.ownerIndex = 1;
        crow.hasCrown = true;
        state.crowMinions.add(crow);

        LanState.ChickMinionState chick = new LanState.ChickMinionState();
        chick.x = 4.0;
        chick.y = 5.0;
        chick.vx = 6.0;
        chick.age = 7;
        chick.ownerIndex = 2;
        chick.variant = 3;
        chick.life = 8;
        chick.ultimate = true;
        chick.followingOwner = true;
        chick.commandFlashFrames = 11;
        chick.thrownFrames = 12;
        chick.boostSparkFrames = 13;
        chick.roosterSwarm = true;
        chick.swarmHitsRemaining = 2;
        chick.swarmVisualCopies = 5;
        state.chickMinions.add(chick);

        LanState.MockingbirdShadowState shadow = new LanState.MockingbirdShadowState();
        shadow.x = 14.0;
        shadow.y = 15.0;
        shadow.vx = 1.25;
        shadow.vy = -2.5;
        shadow.age = 16;
        shadow.ownerIndex = 1;
        shadow.copiedTypeOrdinal = BirdGame3.BirdType.EAGLE.ordinal();
        shadow.health = 9.5;
        shadow.maxHealth = 18.0;
        shadow.attackCooldown = 17;
        shadow.jumpCooldown = 18;
        shadow.retargetCooldown = 19;
        shadow.hitFlashTimer = 20;
        shadow.spawnFlashFrames = 21;
        shadow.onGround = true;
        shadow.facingRight = false;
        shadow.slot = 2;
        state.mockingbirdShadows.add(shadow);

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        state.write(new DataOutputStream(bos));

        LanState decoded = LanState.read(new DataInputStream(new ByteArrayInputStream(bos.toByteArray())));

        assertEquals(321, decoded.matchTimer);
        assertTrue(decoded.matchEnded);
        assertTrue(decoded.suddenDeathActive);
        assertTrue(decoded.suddenDeathSmashStyle);
        assertEquals(3, decoded.activePlayers);
        assertEquals(0.8, decoded.zoom);
        assertEquals(20, decoded.scores[1]);
        assertEquals(List.of("P1 KO", "P2 KO"), decoded.killFeed);
        assertNotNull(decoded.birds[0]);
        assertEquals(2, decoded.birds[0].typeOrdinal);
        assertEquals(12.5, decoded.birds[0].x);
        assertTrue(decoded.birds[0].aerialAttackActive);
        assertEquals(12, decoded.birds[0].aerialAttackTotalFrames);
        assertEquals(5, decoded.birds[0].landingLagTimer);
        assertTrue(decoded.birds[0].isCitySkin);
        assertEquals(2, decoded.birds[0].jumpSquatTimer);
        assertTrue(decoded.birds[0].shortHopQueued);
        assertTrue(decoded.birds[0].isBlocking);
        assertEquals(11, decoded.birds[0].blockCooldown);
        assertEquals(37.5, decoded.birds[0].shieldHealth);
        assertEquals(8, decoded.birds[0].shieldStunFrames);
        assertEquals(2, decoded.birds[0].parryWindowFrames);
        assertEquals(0.65, decoded.birds[0].shieldHoldVisual);
        assertEquals(4, decoded.birds[0].techBufferTimer);
        assertEquals(22, decoded.birds[0].knockdownTimer);
        assertEquals(9, decoded.birds[0].razorbillStormTimer);
        assertEquals(31, decoded.birds[0].razorbillStormHoldFrames);
        assertEquals(17, decoded.birds[0].razorbillStormReuseTimer);
        assertTrue(decoded.birds[0].razorbillStormUltimate);
        assertTrue(decoded.birds[0].razorbillStormReleased);
        assertEquals(6, decoded.birds[0].razorbillStormHitCooldown[2]);
        assertEquals(19, decoded.birds[0].razorbillSideReuseTimer);
        assertTrue(decoded.birds[0].razorbillSideSpecialUsed);
        assertTrue(decoded.birds[0].razorbillSideUltimate);
        assertEquals(11, decoded.birds[0].razorbillShearTimer);
        assertEquals(1, decoded.birds[0].razorbillShearDirection);
        assertTrue(decoded.birds[0].razorbillShearUltimate);
        assertTrue(decoded.birds[0].razorbillUpSpecialUsed);
        assertEquals(7, decoded.birds[0].razorbillCounterTimer);
        assertEquals(23, decoded.birds[0].razorbillCounterReuseTimer);
        assertEquals(5, decoded.birds[0].razorbillCounterWhiffTimer);
        assertEquals(4, decoded.birds[0].razorbillCounterBurstTimer);
        assertTrue(decoded.birds[0].razorbillCounterUltimate);
        assertTrue(decoded.birds[0].razorbillCountered);
        assertTrue(decoded.birds[0].razorbillCounterAttemptActive);
        assertEquals(97, decoded.birds[0].razorbillGuillotineTimer);
        assertEquals(3, decoded.birds[0].razorbillGuillotineSlashIndex);
        assertEquals(88, decoded.birds[0].razorbillGuillotineWakeTimer);
        assertTrue(decoded.birds[0].razorbillGuillotineFinalResolved);
        assertEquals(111.25, decoded.birds[0].razorbillGuillotineAnchorX);
        assertEquals(222.5, decoded.birds[0].razorbillGuillotineAnchorY);
        assertEquals(333.75, decoded.birds[0].razorbillGuillotineTargetX);
        assertEquals(444.0, decoded.birds[0].razorbillGuillotineTargetY);
        assertEquals(555.25, decoded.birds[0].razorbillGuillotineLastStartX);
        assertEquals(666.5, decoded.birds[0].razorbillGuillotineLastStartY);
        assertEquals(777.75, decoded.birds[0].razorbillGuillotineLastEndX);
        assertEquals(888.0, decoded.birds[0].razorbillGuillotineLastEndY);
        assertEquals(120.5, decoded.birds[0].razorbillGuillotineWakeX1);
        assertEquals(480.25, decoded.birds[0].razorbillGuillotineWakeX2);
        assertEquals(910.75, decoded.birds[0].razorbillGuillotineWakeY);
        assertEquals(5, decoded.birds[0].razorbillGuillotineHitCooldown[1]);
        assertEquals(13, decoded.birds[0].razorbillGuillotineWakeHitCooldown[3]);
        assertEquals(2, decoded.birds[0].pelicanCargoCount);
        assertEquals(8, decoded.birds[0].pelicanNeutralTimer);
        assertEquals(12, decoded.birds[0].pelicanNeutralReuseTimer);
        assertTrue(decoded.birds[0].pelicanNeutralUltimate);
        assertTrue(decoded.birds[0].pelicanNeutralHit[1]);
        assertEquals(14, decoded.birds[0].pelicanSideTimer);
        assertEquals(21, decoded.birds[0].pelicanSideReuseTimer);
        assertEquals(-1, decoded.birds[0].pelicanSideDirection);
        assertEquals(2, decoded.birds[0].pelicanSideCargoSpent);
        assertTrue(decoded.birds[0].pelicanSideUltimate);
        assertTrue(decoded.birds[0].pelicanSideHit[2]);
        assertEquals(17, decoded.birds[0].pelicanUpTimer);
        assertTrue(decoded.birds[0].pelicanUpSpecialUsed);
        assertTrue(decoded.birds[0].pelicanUpUltimate);
        assertTrue(decoded.birds[0].pelicanKeelDiveActive);
        assertTrue(decoded.birds[0].pelicanUpHit[3]);
        assertTrue(decoded.birds[0].pelicanDownCharging);
        assertEquals(19, decoded.birds[0].pelicanDownHoldFrames);
        assertEquals(25, decoded.birds[0].pelicanDownReuseTimer);
        assertTrue(decoded.birds[0].pelicanDownUltimate);
        assertEquals(9, decoded.birds[0].pelicanBilgeFxTimer);
        assertEquals(2, decoded.birds[0].pelicanBilgeCargoSpent);
        assertTrue(decoded.birds[0].pelicanBilgeUltimate);
        assertEquals(144, decoded.birds[0].pelicanFullHoldTimer);
        assertEquals(88, decoded.birds[0].pelicanMaelstromTimer);
        assertEquals(5, decoded.birds[0].pelicanMaelstromPulseCooldown);
        assertTrue(decoded.birds[0].pelicanMaelstromFinalResolved);
        assertEquals(2, decoded.birds[0].pelicanMaelstromCargoSpent);
        assertEquals(1234.5, decoded.birds[0].pelicanMaelstromX);
        assertEquals(2222.25, decoded.birds[0].pelicanMaelstromY);
        assertEquals(33, decoded.birds[0].pelicanMaelstromGeyserFxTimer);
        assertTrue(decoded.birds[0].pelicanMaelstromFinalHit[2]);
        assertEquals(13, decoded.birds[0].batWingcutTimer);
        assertTrue(decoded.birds[0].batWingcutFromHang);
        assertTrue(decoded.birds[0].batMoonriseUsed);
        assertTrue(decoded.birds[0].batSilentFromHang);
        assertEquals(77, decoded.birds[0].batCathedralTimer);
        assertTrue(decoded.birds[0].pigeonCoronationActive);
        assertEquals(123, decoded.birds[0].pigeonCoronationTimer);
        assertEquals(456.5, decoded.birds[0].pigeonCoronationX);
        assertEquals(789.25, decoded.birds[0].pigeonCoronationY);
        assertTrue(decoded.birds[0].pigeonCoronationFinalResolved);
        assertFalse(decoded.birds[0].pigeonCoronationStayedInside);
        assertEquals(17, decoded.birds[0].pigeonCoronationTickCooldown[2]);
        assertTrue(decoded.birds[0].pigeonCoronationFinalHit[1]);
        assertTrue(decoded.birds[0].pigeonFeatherCharging);
        assertEquals(41, decoded.birds[0].pigeonFeatherChargeFrames);
        assertEquals(23, decoded.birds[0].pigeonFeatherBurstChargeFrames);
        assertEquals(64, decoded.birds[0].pigeonScavengeTimer);
        assertEquals(36, decoded.birds[0].pigeonScavengeHoldFrames);
        assertTrue(decoded.birds[0].pigeonScavengeAirborne);
        assertEquals(8, decoded.birds[0].pigeonScavengeHitCooldown[3]);
        assertTrue(decoded.birds[0].raptorEggCharging);
        assertEquals(31, decoded.birds[0].raptorEggChargeFrames);
        assertEquals(-1, decoded.birds[0].raptorEggDirection);
        assertTrue(decoded.birds[0].raptorEggActive[2]);
        assertEquals(345.25, decoded.birds[0].raptorEggX[2]);
        assertEquals(456.5, decoded.birds[0].raptorEggY[2]);
        assertEquals(-15.75, decoded.birds[0].raptorEggVX[2]);
        assertEquals(1.25, decoded.birds[0].raptorEggVY[2]);
        assertEquals(0.75, decoded.birds[0].raptorEggPower[2]);
        assertEquals(52, decoded.birds[0].raptorEggLife[2]);
        assertTrue(decoded.birds[0].raptorRushCharging);
        assertEquals(22, decoded.birds[0].raptorRushChargeFrames);
        assertEquals(0.625, decoded.birds[0].raptorRushChargeRatio);
        assertTrue(decoded.birds[0].eagleSkySovereignActive);
        assertTrue(decoded.birds[0].eagleSkySovereignDiving);
        assertEquals(19, decoded.birds[0].eagleSkySovereignTimer);
        assertEquals(321.5, decoded.birds[0].eagleSkySovereignTargetX);
        assertEquals(654.25, decoded.birds[0].eagleSkySovereignTargetY);
        assertEquals(88.75, decoded.birds[0].eagleSkySovereignDiveStartY);
        assertFalse(decoded.birds[0].eagleSkySovereignHitResolved);
        assertTrue(decoded.birds[0].eagleSkySovereignHit[3]);
        assertTrue(decoded.birds[0].falconTerminalVelocityActive);
        assertTrue(decoded.birds[0].falconTerminalVelocityStriking);
        assertTrue(decoded.birds[0].falconTerminalVelocityHitAny);
        assertEquals(6, decoded.birds[0].falconTerminalVelocityTimer);
        assertEquals(-1, decoded.birds[0].falconTerminalVelocityDirection);
        assertEquals(701.5, decoded.birds[0].falconTerminalVelocityStartX);
        assertEquals(202.25, decoded.birds[0].falconTerminalVelocityStartY);
        assertEquals(118.75, decoded.birds[0].falconTerminalVelocityEndX);
        assertEquals(515.5, decoded.birds[0].falconTerminalVelocityEndY);
        assertTrue(decoded.birds[0].falconTerminalVelocityHit[2]);
        assertEquals(77, decoded.birds[0].penguinAbsoluteZeroTimer);
        assertEquals(3, decoded.birds[0].penguinAbsoluteZeroWaveIndex);
        assertEquals(432.25, decoded.birds[0].penguinAbsoluteZeroThroneX);
        assertEquals(876.5, decoded.birds[0].penguinAbsoluteZeroThroneY);
        assertEquals(88, decoded.birds[0].shoebillFinalStillnessTimer);
        assertEquals(2, decoded.birds[0].shoebillFinalStillnessTargetIndex);
        assertEquals(600.25, decoded.birds[0].shoebillFinalStillnessStatueX);
        assertEquals(1200.5, decoded.birds[0].shoebillFinalStillnessStatueY);
        assertEquals(610.75, decoded.birds[0].shoebillFinalStillnessBeamStartX);
        assertEquals(930.25, decoded.birds[0].shoebillFinalStillnessBeamStartY);
        assertEquals(720.5, decoded.birds[0].shoebillFinalStillnessBeamTargetX);
        assertEquals(880.75, decoded.birds[0].shoebillFinalStillnessBeamTargetY);
        assertTrue(decoded.birds[0].shoebillFinalStillnessBeamResolved);
        assertEquals(91, decoded.birds[0].turkeyHarvestTribunalTimer);
        assertEquals(555.25, decoded.birds[0].turkeyHarvestTribunalX);
        assertEquals(777.5, decoded.birds[0].turkeyHarvestTribunalY);
        assertTrue(decoded.birds[0].turkeyHarvestTribunalFinalResolved);
        assertTrue(decoded.birds[0].turkeyHarvestTribunalFinalHit[2]);
        assertEquals(73, decoded.birds[0].roadrunnerRedlineTimer);
        assertEquals(8, decoded.birds[0].roadrunnerRedlineRecoveryTimer);
        assertTrue(decoded.birds[0].roadrunnerRedlineCinematic);
        assertEquals(-1, decoded.birds[0].roadrunnerRedlineDirection);
        assertEquals(4, decoded.birds[0].roadrunnerRedlineStrikeIndex);
        assertTrue(decoded.birds[0].roadrunnerRedlineFinalResolved);
        assertEquals(101.25, decoded.birds[0].roadrunnerRedlineStartX);
        assertEquals(202.5, decoded.birds[0].roadrunnerRedlineStartY);
        assertEquals(303.75, decoded.birds[0].roadrunnerRedlineEndX);
        assertEquals(404.0, decoded.birds[0].roadrunnerRedlineEndY);
        assertEquals(505.25, decoded.birds[0].roadrunnerRedlineAnchorX);
        assertEquals(606.5, decoded.birds[0].roadrunnerRedlineAnchorY);
        assertEquals(707.75, decoded.birds[0].roadrunnerRedlineLastStartX);
        assertEquals(808.0, decoded.birds[0].roadrunnerRedlineLastStartY);
        assertEquals(909.25, decoded.birds[0].roadrunnerRedlineLastEndX);
        assertEquals(1001.5, decoded.birds[0].roadrunnerRedlineLastEndY);
        assertTrue(decoded.birds[0].roadrunnerRedlineCaught[2]);
        assertTrue(decoded.birds[0].grinchSleighActive);
        assertEquals(88, decoded.birds[0].grinchSleighTimer);
        assertEquals(-1, decoded.birds[0].grinchSleighDirection);
        assertEquals(333.25, decoded.birds[0].grinchSleighX);
        assertEquals(444.5, decoded.birds[0].grinchSleighY);
        assertTrue(decoded.birds[0].grinchPresentActive);
        assertEquals(555.75, decoded.birds[0].grinchPresentX);
        assertEquals(666.25, decoded.birds[0].grinchPresentY);
        assertTrue(decoded.birds[0].grinchPresentUltimate);
        assertEquals(19, decoded.birds[0].grinchPresentAgeFrames);
        assertEquals(77, decoded.birds[0].grinchPresentFuseFrames);
        assertEquals(123, decoded.birds[0].grinchGiftstormTimer);
        assertEquals(4, decoded.birds[0].grinchGiftstormDropIndex);
        assertTrue(decoded.birds[0].grinchGiftstormFinalResolved);
        assertEquals(-1, decoded.birds[0].grinchGiftstormDirection);
        assertEquals(701.25, decoded.birds[0].grinchGiftstormSleighX);
        assertEquals(202.5, decoded.birds[0].grinchGiftstormSleighY);
        assertEquals(111.25, decoded.birds[0].grinchGiftstormFinalStartX);
        assertEquals(222.5, decoded.birds[0].grinchGiftstormFinalStartY);
        assertEquals(333.75, decoded.birds[0].grinchGiftstormFinalEndX);
        assertEquals(444.0, decoded.birds[0].grinchGiftstormFinalEndY);
        assertEquals(2, decoded.birds[0].grinchGiftstormLastDropKind);
        assertEquals(18, decoded.birds[0].grinchGiftstormDropFxTimer);
        assertTrue(decoded.birds[0].grinchGiftstormFinalHit[1]);
        assertEquals(44, decoded.birds[0].carrionSwarmTimer);
        assertEquals(99, decoded.birds[0].vultureBlackSkyTimer);
        assertEquals(7, decoded.birds[0].vultureBlackSkySpawnTimer);
        assertEquals(31, decoded.birds[0].vultureBlackSkyCrowsSpawned);
        assertEquals(5, decoded.birds[0].vultureBlackSkyWaveIndex);
        assertTrue(decoded.birds[0].vultureBlackSkyFinalHit);
        assertTrue(decoded.birds[0].vultureBlackSkyHit[3]);
        assertEquals(66, decoded.birds[0].hummingFrenzyTimer);
        assertEquals(1, decoded.birds[0].hummingFrenzyTargetIndex);
        assertEquals(3, decoded.birds[0].hummingFrenzyStrikeIndex);
        assertEquals(2, decoded.birds[0].hummingFrenzyConnectedStrikes);
        assertTrue(decoded.birds[0].hummingFrenzyFinalResolved);
        assertEquals(121.25, decoded.birds[0].hummingFrenzyAnchorX);
        assertEquals(242.5, decoded.birds[0].hummingFrenzyAnchorY);
        assertEquals(363.75, decoded.birds[0].hummingFrenzyTargetX);
        assertEquals(484.0, decoded.birds[0].hummingFrenzyTargetY);
        assertEquals(605.25, decoded.birds[0].hummingFrenzyLastStartX);
        assertEquals(726.5, decoded.birds[0].hummingFrenzyLastStartY);
        assertEquals(847.75, decoded.birds[0].hummingFrenzyLastEndX);
        assertEquals(968.0, decoded.birds[0].hummingFrenzyLastEndY);
        assertEquals(5, decoded.birds[0].hummingFrenzyHitCooldown[1]);
        assertEquals(44.0, decoded.birds[0].ultimateMeter);
        assertEquals(1, decoded.powerUps.size());
        assertEquals(200.0, decoded.powerUps.getFirst().x);
        assertFalse(decoded.nectarNodes.getFirst().active);
        assertEquals(33.0, decoded.swingingVines.getFirst().length);
        assertEquals(4, decoded.windVents.getFirst().cooldown);
        assertTrue(decoded.crowMinions.getFirst().hasCrown);
        assertTrue(decoded.chickMinions.getFirst().ultimate);
        assertTrue(decoded.chickMinions.getFirst().followingOwner);
        assertEquals(11, decoded.chickMinions.getFirst().commandFlashFrames);
        assertEquals(12, decoded.chickMinions.getFirst().thrownFrames);
        assertEquals(13, decoded.chickMinions.getFirst().boostSparkFrames);
        assertTrue(decoded.chickMinions.getFirst().roosterSwarm);
        assertEquals(2, decoded.chickMinions.getFirst().swarmHitsRemaining);
        assertEquals(5, decoded.chickMinions.getFirst().swarmVisualCopies);
        assertEquals(1, decoded.mockingbirdShadows.size());
        assertEquals(14.0, decoded.mockingbirdShadows.getFirst().x);
        assertEquals(-2.5, decoded.mockingbirdShadows.getFirst().vy);
        assertEquals(BirdGame3.BirdType.EAGLE.ordinal(), decoded.mockingbirdShadows.getFirst().copiedTypeOrdinal);
        assertEquals(9.5, decoded.mockingbirdShadows.getFirst().health);
        assertEquals(18.0, decoded.mockingbirdShadows.getFirst().maxHealth);
        assertEquals(17, decoded.mockingbirdShadows.getFirst().attackCooldown);
        assertEquals(21, decoded.mockingbirdShadows.getFirst().spawnFlashFrames);
        assertTrue(decoded.mockingbirdShadows.getFirst().onGround);
        assertFalse(decoded.mockingbirdShadows.getFirst().facingRight);
        assertEquals(2, decoded.mockingbirdShadows.getFirst().slot);
    }
}
