package com.example.birdgame3;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

class LanBirdState {
    int typeOrdinal;
    double x;
    double y;
    double vx;
    double vy;
    boolean facingRight;
    double health;
    double stunTime;
    int specialCooldown;
    int specialMaxCooldown;
    int attackCooldown;
    int attackAnimationTimer;
    boolean canDoubleJump;
    boolean loungeActive;
    boolean isCitySkin;
    boolean isNoirSkin;
    boolean isFreemanSkin;
    boolean isClassicSkin;
    boolean isNovaSkin;
    boolean isDuneSkin;
    boolean isMintSkin;
    boolean isCircuitSkin;
    boolean isPrismSkin;
    boolean isAuroraSkin;
    boolean isBeaconSkin;
    boolean isSunflareSkin;
    boolean isGlacierSkin;
    boolean isTideSkin;
    boolean isEclipseSkin;
    boolean isUmbraSkin;
    boolean isSunforgeSkin;
    boolean suppressSelectEffects;
    double loungeX;
    double loungeY;
    int loungeHealth;
    int loungeMaxHealth;
    int loungeDamageFlash;
    boolean loungeRoyal;
    int diveTimer;
    boolean isZipping;
    double zipTargetX;
    double zipTargetY;
    int zipTimer;
    boolean isGroundPounding;
    int carrionSwarmTimer;
    int crowSwarmCooldown;
    boolean isFlying;
    int leanTimer;
    int leanCooldown;
    boolean isHigh;
    int highTimer;
    int tauntCooldown;
    int tauntTimer;
    int cooldownFlash;
    int currentTaunt;
    int eagleDiveCountdown;
    boolean eagleDiveActive;
    boolean eagleAscentActive;
    int eagleAscentFrames;
    int bladeStormFrames;
    int plungeTimer;
    boolean batHanging;
    int batEchoTimer;
    boolean isBlocking;
    int blockCooldown;
    double speedMultiplier;
    double powerMultiplier;
    double sizeMultiplier;
    double baseSpeedMultiplier;
    double basePowerMultiplier;
    double baseSizeMultiplier;
    int speedTimer;
    int rageTimer;
    int shrinkTimer;
    int titanTimer;
    boolean titanActive;
    int neonRushTimer;
    int thermalTimer;
    double thermalLift;
    int overchargeAttackTimer;
    double speedBoostTimer;
    double hoverRegenTimer;
    double hoverRegenMultiplier;
    int grappleTimer;
    int grappleUses;
    boolean isGrappling;
    double grappleTargetX;
    double grappleTargetY;
    boolean enlargedByPlunge;
    double limitedFlightFuel;
    double penguinIceFxTimer;
    int penguinDashDamageTimer;
    int hummingFrenzyTimer;
    int phoenixAfterburnTimer;
    boolean phoenixRebornUsed;
    boolean phoenixRebornActive;
    double ultimateMeter;
    int ultimateFxTimer;

    void write(DataOutputStream out) throws IOException {
        out.writeInt(typeOrdinal);
        out.writeDouble(x);
        out.writeDouble(y);
        out.writeDouble(vx);
        out.writeDouble(vy);
        out.writeBoolean(facingRight);
        out.writeDouble(health);
        out.writeDouble(stunTime);
        out.writeInt(specialCooldown);
        out.writeInt(specialMaxCooldown);
        out.writeInt(attackCooldown);
        out.writeInt(attackAnimationTimer);
        out.writeBoolean(canDoubleJump);
        out.writeBoolean(loungeActive);
        out.writeBoolean(isCitySkin);
        out.writeBoolean(isNoirSkin);
        out.writeBoolean(isFreemanSkin);
        out.writeBoolean(isClassicSkin);
        out.writeBoolean(isNovaSkin);
        out.writeBoolean(isDuneSkin);
        out.writeBoolean(isMintSkin);
        out.writeBoolean(isCircuitSkin);
        out.writeBoolean(isPrismSkin);
        out.writeBoolean(isAuroraSkin);
        out.writeBoolean(isBeaconSkin);
        out.writeBoolean(isSunflareSkin);
        out.writeBoolean(isGlacierSkin);
        out.writeBoolean(isTideSkin);
        out.writeBoolean(isEclipseSkin);
        out.writeBoolean(isUmbraSkin);
        out.writeBoolean(isSunforgeSkin);
        out.writeBoolean(suppressSelectEffects);
        out.writeDouble(loungeX);
        out.writeDouble(loungeY);
        out.writeInt(loungeHealth);
        out.writeInt(loungeMaxHealth);
        out.writeInt(loungeDamageFlash);
        out.writeBoolean(loungeRoyal);
        out.writeInt(diveTimer);
        out.writeBoolean(isZipping);
        out.writeDouble(zipTargetX);
        out.writeDouble(zipTargetY);
        out.writeInt(zipTimer);
        out.writeBoolean(isGroundPounding);
        out.writeInt(carrionSwarmTimer);
        out.writeInt(crowSwarmCooldown);
        out.writeBoolean(isFlying);
        out.writeInt(leanTimer);
        out.writeInt(leanCooldown);
        out.writeBoolean(isHigh);
        out.writeInt(highTimer);
        out.writeInt(tauntCooldown);
        out.writeInt(tauntTimer);
        out.writeInt(cooldownFlash);
        out.writeInt(currentTaunt);
        out.writeInt(eagleDiveCountdown);
        out.writeBoolean(eagleDiveActive);
        out.writeBoolean(eagleAscentActive);
        out.writeInt(eagleAscentFrames);
        out.writeInt(bladeStormFrames);
        out.writeInt(plungeTimer);
        out.writeBoolean(batHanging);
        out.writeInt(batEchoTimer);
        out.writeBoolean(isBlocking);
        out.writeInt(blockCooldown);
        out.writeDouble(speedMultiplier);
        out.writeDouble(powerMultiplier);
        out.writeDouble(sizeMultiplier);
        out.writeDouble(baseSpeedMultiplier);
        out.writeDouble(basePowerMultiplier);
        out.writeDouble(baseSizeMultiplier);
        out.writeInt(speedTimer);
        out.writeInt(rageTimer);
        out.writeInt(shrinkTimer);
        out.writeInt(titanTimer);
        out.writeBoolean(titanActive);
        out.writeInt(neonRushTimer);
        out.writeInt(thermalTimer);
        out.writeDouble(thermalLift);
        out.writeInt(overchargeAttackTimer);
        out.writeDouble(speedBoostTimer);
        out.writeDouble(hoverRegenTimer);
        out.writeDouble(hoverRegenMultiplier);
        out.writeInt(grappleTimer);
        out.writeInt(grappleUses);
        out.writeBoolean(isGrappling);
        out.writeDouble(grappleTargetX);
        out.writeDouble(grappleTargetY);
        out.writeBoolean(enlargedByPlunge);
        out.writeDouble(limitedFlightFuel);
        out.writeDouble(penguinIceFxTimer);
        out.writeInt(penguinDashDamageTimer);
        out.writeInt(hummingFrenzyTimer);
        out.writeInt(phoenixAfterburnTimer);
        out.writeBoolean(phoenixRebornUsed);
        out.writeBoolean(phoenixRebornActive);
        out.writeDouble(ultimateMeter);
        out.writeInt(ultimateFxTimer);
    }

    static LanBirdState read(DataInputStream in) throws IOException {
        LanBirdState state = new LanBirdState();
        state.typeOrdinal = in.readInt();
        state.x = in.readDouble();
        state.y = in.readDouble();
        state.vx = in.readDouble();
        state.vy = in.readDouble();
        state.facingRight = in.readBoolean();
        state.health = in.readDouble();
        state.stunTime = in.readDouble();
        state.specialCooldown = in.readInt();
        state.specialMaxCooldown = in.readInt();
        state.attackCooldown = in.readInt();
        state.attackAnimationTimer = in.readInt();
        state.canDoubleJump = in.readBoolean();
        state.loungeActive = in.readBoolean();
        state.isCitySkin = in.readBoolean();
        state.isNoirSkin = in.readBoolean();
        state.isFreemanSkin = in.readBoolean();
        state.isClassicSkin = in.readBoolean();
        state.isNovaSkin = in.readBoolean();
        state.isDuneSkin = in.readBoolean();
        state.isMintSkin = in.readBoolean();
        state.isCircuitSkin = in.readBoolean();
        state.isPrismSkin = in.readBoolean();
        state.isAuroraSkin = in.readBoolean();
        state.isBeaconSkin = in.readBoolean();
        state.isSunflareSkin = in.readBoolean();
        state.isGlacierSkin = in.readBoolean();
        state.isTideSkin = in.readBoolean();
        state.isEclipseSkin = in.readBoolean();
        state.isUmbraSkin = in.readBoolean();
        state.isSunforgeSkin = in.readBoolean();
        state.suppressSelectEffects = in.readBoolean();
        state.loungeX = in.readDouble();
        state.loungeY = in.readDouble();
        state.loungeHealth = in.readInt();
        state.loungeMaxHealth = in.readInt();
        state.loungeDamageFlash = in.readInt();
        state.loungeRoyal = in.readBoolean();
        state.diveTimer = in.readInt();
        state.isZipping = in.readBoolean();
        state.zipTargetX = in.readDouble();
        state.zipTargetY = in.readDouble();
        state.zipTimer = in.readInt();
        state.isGroundPounding = in.readBoolean();
        state.carrionSwarmTimer = in.readInt();
        state.crowSwarmCooldown = in.readInt();
        state.isFlying = in.readBoolean();
        state.leanTimer = in.readInt();
        state.leanCooldown = in.readInt();
        state.isHigh = in.readBoolean();
        state.highTimer = in.readInt();
        state.tauntCooldown = in.readInt();
        state.tauntTimer = in.readInt();
        state.cooldownFlash = in.readInt();
        state.currentTaunt = in.readInt();
        state.eagleDiveCountdown = in.readInt();
        state.eagleDiveActive = in.readBoolean();
        state.eagleAscentActive = in.readBoolean();
        state.eagleAscentFrames = in.readInt();
        state.bladeStormFrames = in.readInt();
        state.plungeTimer = in.readInt();
        state.batHanging = in.readBoolean();
        state.batEchoTimer = in.readInt();
        state.isBlocking = in.readBoolean();
        state.blockCooldown = in.readInt();
        state.speedMultiplier = in.readDouble();
        state.powerMultiplier = in.readDouble();
        state.sizeMultiplier = in.readDouble();
        state.baseSpeedMultiplier = in.readDouble();
        state.basePowerMultiplier = in.readDouble();
        state.baseSizeMultiplier = in.readDouble();
        state.speedTimer = in.readInt();
        state.rageTimer = in.readInt();
        state.shrinkTimer = in.readInt();
        state.titanTimer = in.readInt();
        state.titanActive = in.readBoolean();
        state.neonRushTimer = in.readInt();
        state.thermalTimer = in.readInt();
        state.thermalLift = in.readDouble();
        state.overchargeAttackTimer = in.readInt();
        state.speedBoostTimer = in.readDouble();
        state.hoverRegenTimer = in.readDouble();
        state.hoverRegenMultiplier = in.readDouble();
        state.grappleTimer = in.readInt();
        state.grappleUses = in.readInt();
        state.isGrappling = in.readBoolean();
        state.grappleTargetX = in.readDouble();
        state.grappleTargetY = in.readDouble();
        state.enlargedByPlunge = in.readBoolean();
        state.limitedFlightFuel = in.readDouble();
        state.penguinIceFxTimer = in.readDouble();
        state.penguinDashDamageTimer = in.readInt();
        state.hummingFrenzyTimer = in.readInt();
        state.phoenixAfterburnTimer = in.readInt();
        state.phoenixRebornUsed = in.readBoolean();
        state.phoenixRebornActive = in.readBoolean();
        state.ultimateMeter = in.readDouble();
        state.ultimateFxTimer = in.readInt();
        return state;
    }
}
