package com.example.birdgame3;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;

class LanBirdState {
    int typeOrdinal;
    double x;
    double y;
    double vx;
    double vy;
    boolean facingRight;
    double health;
    double smashDamage;
    double stunTime;
    int specialCooldown;
    int specialMaxCooldown;
    int attackCooldown;
    int attackAnimationTimer;
    int attackChargeFrames;
    int pendingGroundAttackFrames;
    int pendingGroundAttackVariantOrdinal;
    int chargingAttackVariantOrdinal;
    int activeAttackVariantOrdinal;
    boolean aerialAttackActive;
    int aerialAttackTotalFrames;
    int activeAerialLandingLagFrames;
    int landingLagTimer;
    boolean canDoubleJump;
    int jumpSquatTimer;
    boolean shortHopQueued;
    boolean loungeActive;
    boolean isCitySkin;
    boolean isNoirSkin;
    boolean isFreemanSkin;
    boolean isClassicSkin;
    boolean isNovaSkin;
    boolean isDuneSkin;
    boolean isMintSkin;
    boolean isCircuitSkin;
    boolean isPrismSkin;
    boolean isAuroraSkin;
    boolean isBeaconSkin;
    boolean isStormSkin;
    boolean isSunflareSkin;
    boolean isGlacierSkin;
    boolean isTideSkin;
    boolean isNullRockSkin;
    boolean isEclipseSkin;
    boolean isUmbraSkin;
    boolean isResonanceSkin;
    boolean isIroncladSkin;
    boolean isSunforgeSkin;
    boolean isPhotoEagleSkin;
    boolean suppressSelectEffects;
    double loungeX;
    double loungeY;
    int loungeHealth;
    int loungeMaxHealth;
    int loungeDamageFlash;
    boolean loungeRoyal;
    int diveTimer;
    boolean isZipping;
    double zipTargetX;
    double zipTargetY;
    int zipTimer;
    boolean isGroundPounding;
    int carrionSwarmTimer;
    int crowSwarmCooldown;
    boolean isFlying;
    int leanTimer;
    int leanCooldown;
    boolean isHigh;
    int highTimer;
    int tauntCooldown;
    int tauntTimer;
    int cooldownFlash;
    int currentTaunt;
    int eagleDiveCountdown;
    boolean eagleDiveActive;
    boolean eagleAscentActive;
    int eagleAscentFrames;
    int bladeStormFrames;
    int plungeTimer;
    boolean batHanging;
    int batEchoTimer;
    int batRehangCooldownTimer;
    boolean ledgeHanging;
    boolean ledgeGrabOnRightSide;
    int ledgeLockTimer;
    int ledgeRegrabCooldownTimer;
    int ledgeInvulnerabilityTimer;
    boolean respawnNestActive;
    double respawnNestX;
    double respawnNestY;
    double respawnNestW;
    double respawnNestH;
    int respawnInvulnerabilityTimer;
    boolean wasOnRespawnNestLastFrame;
    boolean isBlocking;
    int blockCooldown;
    double shieldHealth = 60.0;
    int shieldStunFrames;
    int parryWindowFrames;
    double shieldHoldVisual;
    int dodgeTypeOrdinal;
    int dodgeTimer;
    int dodgeInvulnerabilityTimer;
    int dodgeCooldown;
    int dodgeDirection;
    boolean airDodgeAvailable = true;
    int techBufferTimer;
    int knockdownTimer;
    double speedMultiplier;
    double powerMultiplier;
    double sizeMultiplier;
    double baseSpeedMultiplier;
    double basePowerMultiplier;
    double baseSizeMultiplier;
    int speedTimer;
    int rageTimer;
    int shrinkTimer;
    int titanTimer;
    boolean titanActive;
    int neonRushTimer;
    int thermalTimer;
    double thermalLift;
    int overchargeAttackTimer;
    int roadrunnerSandstormTimer;
    int roadrunnerSandGustTimer;
    int[] roadrunnerSandHitCooldown = new int[4];
    int pigeonFeatherBurstTimer;
    boolean pigeonFeatherBurstUltimate;
    int pigeonRushTimer;
    boolean pigeonRushGrounded;
    boolean pigeonRushUltimate;
    boolean[] pigeonRushHit = new boolean[4];
    int pigeonFlutterTimer;
    boolean pigeonFlutterUltimate;
    boolean[] pigeonFlutterHit = new boolean[4];
    int pigeonScavengeTimer;
    boolean pigeonScavengeAirborne;
    boolean pigeonScavengeUltimate;
    boolean pigeonScavengeResolved;
    boolean pigeonUpSpecialUsed;
    int raptorCryTimer;
    boolean raptorCryUltimate;
    int raptorRushTimer;
    boolean raptorRushUltimate;
    boolean raptorRushGrounded;
    int raptorRushDirection;
    boolean[] raptorRushHit = new boolean[4];
    int raptorClimbTimer;
    boolean raptorClimbUltimate;
    int raptorClimbDirection;
    boolean[] raptorClimbHit = new boolean[4];
    int raptorCryReuseTimer;
    int raptorRushReuseTimer;
    boolean raptorUpSpecialUsed;
    double speedBoostTimer;
    double hoverRegenTimer;
    double hoverRegenMultiplier;
    int grappleTimer;
    int grappleUses;
    boolean isGrappling;
    double grappleTargetX;
    double grappleTargetY;
    boolean enlargedByPlunge;
    double limitedFlightFuel;
    double penguinIceFxTimer;
    int penguinDashDamageTimer;
    int hummingFrenzyTimer;
    int phoenixAfterburnTimer;
    boolean phoenixRebornUsed;
    boolean phoenixRebornActive;
    int phoenixChargeTimer;
    boolean phoenixCharging;
    int phoenixFireballTimer;
    double phoenixFireballX;
    double phoenixFireballY;
    double phoenixFireballVX;
    double phoenixFireballVY;
    boolean phoenixFireballUltimate;
    int phoenixSpiralTimer;
    boolean phoenixSpiralUsed;
    int phoenixLavaTimer;
    double phoenixLavaX;
    double phoenixLavaY;
    boolean phoenixLavaUltimate;
    boolean[] phoenixLavaHitCooldown = new boolean[4];
    double ultimateMeter;
    int ultimateFxTimer;
    int nullRockInvincibilityTimer;
    int nullRockPhaseIndex;

    void write(DataOutputStream out) throws IOException {
        out.writeInt(typeOrdinal);
        out.writeDouble(x);
        out.writeDouble(y);
        out.writeDouble(vx);
        out.writeDouble(vy);
        out.writeBoolean(facingRight);
        out.writeDouble(health);
        out.writeDouble(smashDamage);
        out.writeDouble(stunTime);
        out.writeInt(specialCooldown);
        out.writeInt(specialMaxCooldown);
        out.writeInt(attackCooldown);
        out.writeInt(attackAnimationTimer);
        out.writeInt(attackChargeFrames);
        out.writeInt(pendingGroundAttackFrames);
        out.writeInt(pendingGroundAttackVariantOrdinal);
        out.writeInt(chargingAttackVariantOrdinal);
        out.writeInt(activeAttackVariantOrdinal);
        out.writeBoolean(aerialAttackActive);
        out.writeInt(aerialAttackTotalFrames);
        out.writeInt(activeAerialLandingLagFrames);
        out.writeInt(landingLagTimer);
        out.writeBoolean(canDoubleJump);
        out.writeInt(jumpSquatTimer);
        out.writeBoolean(shortHopQueued);
        out.writeBoolean(loungeActive);
        out.writeBoolean(isCitySkin);
        out.writeBoolean(isNoirSkin);
        out.writeBoolean(isFreemanSkin);
        out.writeBoolean(isClassicSkin);
        out.writeBoolean(isNovaSkin);
        out.writeBoolean(isDuneSkin);
        out.writeBoolean(isMintSkin);
        out.writeBoolean(isCircuitSkin);
        out.writeBoolean(isPrismSkin);
        out.writeBoolean(isAuroraSkin);
        out.writeBoolean(isBeaconSkin);
        out.writeBoolean(isStormSkin);
        out.writeBoolean(isSunflareSkin);
        out.writeBoolean(isGlacierSkin);
        out.writeBoolean(isTideSkin);
        out.writeBoolean(isNullRockSkin);
        out.writeBoolean(isEclipseSkin);
        out.writeBoolean(isUmbraSkin);
        out.writeBoolean(isResonanceSkin);
        out.writeBoolean(isIroncladSkin);
        out.writeBoolean(isSunforgeSkin);
        out.writeBoolean(isPhotoEagleSkin);
        out.writeBoolean(suppressSelectEffects);
        out.writeDouble(loungeX);
        out.writeDouble(loungeY);
        out.writeInt(loungeHealth);
        out.writeInt(loungeMaxHealth);
        out.writeInt(loungeDamageFlash);
        out.writeBoolean(loungeRoyal);
        out.writeInt(diveTimer);
        out.writeBoolean(isZipping);
        out.writeDouble(zipTargetX);
        out.writeDouble(zipTargetY);
        out.writeInt(zipTimer);
        out.writeBoolean(isGroundPounding);
        out.writeInt(carrionSwarmTimer);
        out.writeInt(crowSwarmCooldown);
        out.writeBoolean(isFlying);
        out.writeInt(leanTimer);
        out.writeInt(leanCooldown);
        out.writeBoolean(isHigh);
        out.writeInt(highTimer);
        out.writeInt(tauntCooldown);
        out.writeInt(tauntTimer);
        out.writeInt(cooldownFlash);
        out.writeInt(currentTaunt);
        out.writeInt(eagleDiveCountdown);
        out.writeBoolean(eagleDiveActive);
        out.writeBoolean(eagleAscentActive);
        out.writeInt(eagleAscentFrames);
        out.writeInt(bladeStormFrames);
        out.writeInt(plungeTimer);
        out.writeBoolean(batHanging);
        out.writeInt(batEchoTimer);
        out.writeInt(batRehangCooldownTimer);
        out.writeBoolean(ledgeHanging);
        out.writeBoolean(ledgeGrabOnRightSide);
        out.writeInt(ledgeLockTimer);
        out.writeInt(ledgeRegrabCooldownTimer);
        out.writeInt(ledgeInvulnerabilityTimer);
        out.writeBoolean(respawnNestActive);
        out.writeDouble(respawnNestX);
        out.writeDouble(respawnNestY);
        out.writeDouble(respawnNestW);
        out.writeDouble(respawnNestH);
        out.writeInt(respawnInvulnerabilityTimer);
        out.writeBoolean(wasOnRespawnNestLastFrame);
        out.writeBoolean(isBlocking);
        out.writeInt(blockCooldown);
        out.writeDouble(shieldHealth);
        out.writeInt(shieldStunFrames);
        out.writeInt(parryWindowFrames);
        out.writeDouble(shieldHoldVisual);
        out.writeInt(dodgeTypeOrdinal);
        out.writeInt(dodgeTimer);
        out.writeInt(dodgeInvulnerabilityTimer);
        out.writeInt(dodgeCooldown);
        out.writeInt(dodgeDirection);
        out.writeBoolean(airDodgeAvailable);
        out.writeInt(techBufferTimer);
        out.writeInt(knockdownTimer);
        out.writeDouble(speedMultiplier);
        out.writeDouble(powerMultiplier);
        out.writeDouble(sizeMultiplier);
        out.writeDouble(baseSpeedMultiplier);
        out.writeDouble(basePowerMultiplier);
        out.writeDouble(baseSizeMultiplier);
        out.writeInt(speedTimer);
        out.writeInt(rageTimer);
        out.writeInt(shrinkTimer);
        out.writeInt(titanTimer);
        out.writeBoolean(titanActive);
        out.writeInt(neonRushTimer);
        out.writeInt(thermalTimer);
        out.writeDouble(thermalLift);
        out.writeInt(overchargeAttackTimer);
        out.writeInt(roadrunnerSandstormTimer);
        out.writeInt(roadrunnerSandGustTimer);
        for (int cooldown : roadrunnerSandHitCooldown) {
            out.writeInt(cooldown);
        }
        out.writeInt(pigeonFeatherBurstTimer);
        out.writeBoolean(pigeonFeatherBurstUltimate);
        out.writeInt(pigeonRushTimer);
        out.writeBoolean(pigeonRushGrounded);
        out.writeBoolean(pigeonRushUltimate);
        for (boolean hit : pigeonRushHit) {
            out.writeBoolean(hit);
        }
        out.writeInt(pigeonFlutterTimer);
        out.writeBoolean(pigeonFlutterUltimate);
        for (boolean hit : pigeonFlutterHit) {
            out.writeBoolean(hit);
        }
        out.writeInt(pigeonScavengeTimer);
        out.writeBoolean(pigeonScavengeAirborne);
        out.writeBoolean(pigeonScavengeUltimate);
        out.writeBoolean(pigeonScavengeResolved);
        out.writeBoolean(pigeonUpSpecialUsed);
        out.writeInt(raptorCryTimer);
        out.writeBoolean(raptorCryUltimate);
        out.writeInt(raptorRushTimer);
        out.writeBoolean(raptorRushUltimate);
        out.writeBoolean(raptorRushGrounded);
        out.writeInt(raptorRushDirection);
        for (boolean hit : raptorRushHit) {
            out.writeBoolean(hit);
        }
        out.writeInt(raptorClimbTimer);
        out.writeBoolean(raptorClimbUltimate);
        out.writeInt(raptorClimbDirection);
        for (boolean hit : raptorClimbHit) {
            out.writeBoolean(hit);
        }
        out.writeInt(raptorCryReuseTimer);
        out.writeInt(raptorRushReuseTimer);
        out.writeBoolean(raptorUpSpecialUsed);
        out.writeDouble(speedBoostTimer);
        out.writeDouble(hoverRegenTimer);
        out.writeDouble(hoverRegenMultiplier);
        out.writeInt(grappleTimer);
        out.writeInt(grappleUses);
        out.writeBoolean(isGrappling);
        out.writeDouble(grappleTargetX);
        out.writeDouble(grappleTargetY);
        out.writeBoolean(enlargedByPlunge);
        out.writeDouble(limitedFlightFuel);
        out.writeDouble(penguinIceFxTimer);
        out.writeInt(penguinDashDamageTimer);
        out.writeInt(hummingFrenzyTimer);
        out.writeInt(phoenixAfterburnTimer);
        out.writeBoolean(phoenixRebornUsed);
        out.writeBoolean(phoenixRebornActive);
        out.writeInt(phoenixChargeTimer);
        out.writeBoolean(phoenixCharging);
        out.writeInt(phoenixFireballTimer);
        out.writeDouble(phoenixFireballX);
        out.writeDouble(phoenixFireballY);
        out.writeDouble(phoenixFireballVX);
        out.writeDouble(phoenixFireballVY);
        out.writeBoolean(phoenixFireballUltimate);
        out.writeInt(phoenixSpiralTimer);
        out.writeBoolean(phoenixSpiralUsed);
        out.writeInt(phoenixLavaTimer);
        out.writeDouble(phoenixLavaX);
        out.writeDouble(phoenixLavaY);
        out.writeBoolean(phoenixLavaUltimate);
        for (boolean hit : phoenixLavaHitCooldown) {
            out.writeBoolean(hit);
        }
        out.writeDouble(ultimateMeter);
        out.writeInt(ultimateFxTimer);
        out.writeInt(nullRockInvincibilityTimer);
        out.writeInt(nullRockPhaseIndex);
    }

    static LanBirdState read(DataInputStream in) throws IOException {
        LanBirdState state = new LanBirdState();
        state.typeOrdinal = in.readInt();
        state.x = in.readDouble();
        state.y = in.readDouble();
        state.vx = in.readDouble();
        state.vy = in.readDouble();
        state.facingRight = in.readBoolean();
        state.health = in.readDouble();
        state.smashDamage = in.readDouble();
        state.stunTime = in.readDouble();
        state.specialCooldown = in.readInt();
        state.specialMaxCooldown = in.readInt();
        state.attackCooldown = in.readInt();
        state.attackAnimationTimer = in.readInt();
        state.attackChargeFrames = in.readInt();
        state.pendingGroundAttackFrames = in.readInt();
        state.pendingGroundAttackVariantOrdinal = in.readInt();
        state.chargingAttackVariantOrdinal = in.readInt();
        state.activeAttackVariantOrdinal = in.readInt();
        state.aerialAttackActive = in.readBoolean();
        state.aerialAttackTotalFrames = in.readInt();
        state.activeAerialLandingLagFrames = in.readInt();
        state.landingLagTimer = in.readInt();
        state.canDoubleJump = in.readBoolean();
        state.jumpSquatTimer = in.readInt();
        state.shortHopQueued = in.readBoolean();
        state.loungeActive = in.readBoolean();
        state.isCitySkin = in.readBoolean();
        state.isNoirSkin = in.readBoolean();
        state.isFreemanSkin = in.readBoolean();
        state.isClassicSkin = in.readBoolean();
        state.isNovaSkin = in.readBoolean();
        state.isDuneSkin = in.readBoolean();
        state.isMintSkin = in.readBoolean();
        state.isCircuitSkin = in.readBoolean();
        state.isPrismSkin = in.readBoolean();
        state.isAuroraSkin = in.readBoolean();
        state.isBeaconSkin = in.readBoolean();
        state.isStormSkin = in.readBoolean();
        state.isSunflareSkin = in.readBoolean();
        state.isGlacierSkin = in.readBoolean();
        state.isTideSkin = in.readBoolean();
        state.isNullRockSkin = in.readBoolean();
        state.isEclipseSkin = in.readBoolean();
        state.isUmbraSkin = in.readBoolean();
        state.isResonanceSkin = in.readBoolean();
        state.isIroncladSkin = in.readBoolean();
        state.isSunforgeSkin = in.readBoolean();
        state.isPhotoEagleSkin = in.readBoolean();
        state.suppressSelectEffects = in.readBoolean();
        state.loungeX = in.readDouble();
        state.loungeY = in.readDouble();
        state.loungeHealth = in.readInt();
        state.loungeMaxHealth = in.readInt();
        state.loungeDamageFlash = in.readInt();
        state.loungeRoyal = in.readBoolean();
        state.diveTimer = in.readInt();
        state.isZipping = in.readBoolean();
        state.zipTargetX = in.readDouble();
        state.zipTargetY = in.readDouble();
        state.zipTimer = in.readInt();
        state.isGroundPounding = in.readBoolean();
        state.carrionSwarmTimer = in.readInt();
        state.crowSwarmCooldown = in.readInt();
        state.isFlying = in.readBoolean();
        state.leanTimer = in.readInt();
        state.leanCooldown = in.readInt();
        state.isHigh = in.readBoolean();
        state.highTimer = in.readInt();
        state.tauntCooldown = in.readInt();
        state.tauntTimer = in.readInt();
        state.cooldownFlash = in.readInt();
        state.currentTaunt = in.readInt();
        state.eagleDiveCountdown = in.readInt();
        state.eagleDiveActive = in.readBoolean();
        state.eagleAscentActive = in.readBoolean();
        state.eagleAscentFrames = in.readInt();
        state.bladeStormFrames = in.readInt();
        state.plungeTimer = in.readInt();
        state.batHanging = in.readBoolean();
        state.batEchoTimer = in.readInt();
        state.batRehangCooldownTimer = in.readInt();
        state.ledgeHanging = in.readBoolean();
        state.ledgeGrabOnRightSide = in.readBoolean();
        state.ledgeLockTimer = in.readInt();
        state.ledgeRegrabCooldownTimer = in.readInt();
        state.ledgeInvulnerabilityTimer = in.readInt();
        state.respawnNestActive = in.readBoolean();
        state.respawnNestX = in.readDouble();
        state.respawnNestY = in.readDouble();
        state.respawnNestW = in.readDouble();
        state.respawnNestH = in.readDouble();
        state.respawnInvulnerabilityTimer = in.readInt();
        state.wasOnRespawnNestLastFrame = in.readBoolean();
        state.isBlocking = in.readBoolean();
        state.blockCooldown = in.readInt();
        state.shieldHealth = in.readDouble();
        state.shieldStunFrames = in.readInt();
        state.parryWindowFrames = in.readInt();
        state.shieldHoldVisual = in.readDouble();
        state.dodgeTypeOrdinal = in.readInt();
        state.dodgeTimer = in.readInt();
        state.dodgeInvulnerabilityTimer = in.readInt();
        state.dodgeCooldown = in.readInt();
        state.dodgeDirection = in.readInt();
        state.airDodgeAvailable = in.readBoolean();
        state.techBufferTimer = in.readInt();
        state.knockdownTimer = in.readInt();
        state.speedMultiplier = in.readDouble();
        state.powerMultiplier = in.readDouble();
        state.sizeMultiplier = in.readDouble();
        state.baseSpeedMultiplier = in.readDouble();
        state.basePowerMultiplier = in.readDouble();
        state.baseSizeMultiplier = in.readDouble();
        state.speedTimer = in.readInt();
        state.rageTimer = in.readInt();
        state.shrinkTimer = in.readInt();
        state.titanTimer = in.readInt();
        state.titanActive = in.readBoolean();
        state.neonRushTimer = in.readInt();
        state.thermalTimer = in.readInt();
        state.thermalLift = in.readDouble();
        state.overchargeAttackTimer = in.readInt();
        state.roadrunnerSandstormTimer = in.readInt();
        state.roadrunnerSandGustTimer = in.readInt();
        for (int i = 0; i < state.roadrunnerSandHitCooldown.length; i++) {
            state.roadrunnerSandHitCooldown[i] = in.readInt();
        }
        state.pigeonFeatherBurstTimer = in.readInt();
        state.pigeonFeatherBurstUltimate = in.readBoolean();
        state.pigeonRushTimer = in.readInt();
        state.pigeonRushGrounded = in.readBoolean();
        state.pigeonRushUltimate = in.readBoolean();
        for (int i = 0; i < state.pigeonRushHit.length; i++) {
            state.pigeonRushHit[i] = in.readBoolean();
        }
        state.pigeonFlutterTimer = in.readInt();
        state.pigeonFlutterUltimate = in.readBoolean();
        for (int i = 0; i < state.pigeonFlutterHit.length; i++) {
            state.pigeonFlutterHit[i] = in.readBoolean();
        }
        state.pigeonScavengeTimer = in.readInt();
        state.pigeonScavengeAirborne = in.readBoolean();
        state.pigeonScavengeUltimate = in.readBoolean();
        state.pigeonScavengeResolved = in.readBoolean();
        state.pigeonUpSpecialUsed = in.readBoolean();
        state.raptorCryTimer = in.readInt();
        state.raptorCryUltimate = in.readBoolean();
        state.raptorRushTimer = in.readInt();
        state.raptorRushUltimate = in.readBoolean();
        state.raptorRushGrounded = in.readBoolean();
        state.raptorRushDirection = in.readInt();
        for (int i = 0; i < state.raptorRushHit.length; i++) {
            state.raptorRushHit[i] = in.readBoolean();
        }
        state.raptorClimbTimer = in.readInt();
        state.raptorClimbUltimate = in.readBoolean();
        state.raptorClimbDirection = in.readInt();
        for (int i = 0; i < state.raptorClimbHit.length; i++) {
            state.raptorClimbHit[i] = in.readBoolean();
        }
        state.raptorCryReuseTimer = in.readInt();
        state.raptorRushReuseTimer = in.readInt();
        state.raptorUpSpecialUsed = in.readBoolean();
        state.speedBoostTimer = in.readDouble();
        state.hoverRegenTimer = in.readDouble();
        state.hoverRegenMultiplier = in.readDouble();
        state.grappleTimer = in.readInt();
        state.grappleUses = in.readInt();
        state.isGrappling = in.readBoolean();
        state.grappleTargetX = in.readDouble();
        state.grappleTargetY = in.readDouble();
        state.enlargedByPlunge = in.readBoolean();
        state.limitedFlightFuel = in.readDouble();
        state.penguinIceFxTimer = in.readDouble();
        state.penguinDashDamageTimer = in.readInt();
        state.hummingFrenzyTimer = in.readInt();
        state.phoenixAfterburnTimer = in.readInt();
        state.phoenixRebornUsed = in.readBoolean();
        state.phoenixRebornActive = in.readBoolean();
        state.phoenixChargeTimer = in.readInt();
        state.phoenixCharging = in.readBoolean();
        state.phoenixFireballTimer = in.readInt();
        state.phoenixFireballX = in.readDouble();
        state.phoenixFireballY = in.readDouble();
        state.phoenixFireballVX = in.readDouble();
        state.phoenixFireballVY = in.readDouble();
        state.phoenixFireballUltimate = in.readBoolean();
        state.phoenixSpiralTimer = in.readInt();
        state.phoenixSpiralUsed = in.readBoolean();
        state.phoenixLavaTimer = in.readInt();
        state.phoenixLavaX = in.readDouble();
        state.phoenixLavaY = in.readDouble();
        state.phoenixLavaUltimate = in.readBoolean();
        for (int i = 0; i < state.phoenixLavaHitCooldown.length; i++) {
            state.phoenixLavaHitCooldown[i] = in.readBoolean();
        }
        state.ultimateMeter = in.readDouble();
        state.ultimateFxTimer = in.readInt();
        state.nullRockInvincibilityTimer = in.readInt();
        state.nullRockPhaseIndex = in.readInt();
        return state;
    }
}
