package com.example.birdgame3;

record WiimoteRawInput(
        boolean connected,
        boolean motionPlusAvailable,
        boolean motionPlusActive,
        boolean nunchukConnected,
        boolean gyroAvailable,
        boolean dpadUp,
        boolean dpadDown,
        boolean dpadLeft,
        boolean dpadRight,
        boolean buttonA,
        boolean buttonB,
        boolean buttonOne,
        boolean buttonTwo,
        boolean buttonPlus,
        boolean buttonMinus,
        boolean buttonHome,
        boolean buttonC,
        boolean buttonZ,
        double remoteAccelX,
        double remoteAccelY,
        double remoteAccelZ,
        double gyroYaw,
        double gyroRoll,
        double gyroPitch,
        double nunchukStickX,
        double nunchukStickY,
        double nunchukAccelX,
        double nunchukAccelY,
        double nunchukAccelZ,
        long sampleNanos,
        String status
) {
    static WiimoteRawInput disconnected(String status) {
        return new WiimoteRawInput(
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0L,
                status
        );
    }
}
